package postgres

import (
	"strings"
	"testing"

	"rowsmith/internal/driver"
)

func strp(s string) *string { return &s }

func TestPGAlterTableSQL(t *testing.T) {
	c := &conn{}
	from := &driver.Table{
		Ref: driver.ObjectRef{Schema: "app", Name: "items"},
		Columns: []driver.Column{
			{Name: "id", Type: "integer", Default: strp("GENERATED BY DEFAULT AS IDENTITY")},
			{Name: "price", Type: "numeric(10,2)", Nullable: true, Default: strp("0")},
			{Name: "legacy", Type: "text", Nullable: true},
		},
		PrimaryKey: []string{"id"},
		Indexes:    []driver.Index{{Name: "items_pkey", Primary: true, Unique: true, Columns: []string{"id"}}},
	}
	to := driver.TableDef{
		Ref: driver.ObjectRef{Schema: "app", Name: "items"},
		Columns: []driver.ColumnDef{
			{Column: driver.Column{Name: "id", Type: "integer", Default: strp("GENERATED BY DEFAULT AS IDENTITY")}, OriginalName: "id"},
			{Column: driver.Column{Name: "amount", Type: "numeric(12,2)", Comment: "in cents"}, OriginalName: "price"},
			{Column: driver.Column{Name: "tags", Type: "text[]", Nullable: true, Default: strp("'{}'")}},
		},
		PrimaryKey: []string{"id"},
		Indexes:    []driver.Index{{Name: "items_tags", Columns: []string{"tags"}, Type: "gin"}},
	}
	stmts, err := c.AlterTableSQL(from, to)
	if err != nil {
		t.Fatal(err)
	}
	joined := strings.Join(stmts, "\n")
	for _, want := range []string{
		`ALTER TABLE "app"."items" DROP COLUMN "legacy"`,
		`ALTER TABLE "app"."items" RENAME COLUMN "price" TO "amount"`,
		`ALTER TABLE "app"."items" ALTER COLUMN "amount" TYPE numeric(12,2) USING "amount"::numeric(12,2)`,
		`ALTER TABLE "app"."items" ALTER COLUMN "amount" SET NOT NULL`,
		`ALTER TABLE "app"."items" ALTER COLUMN "amount" DROP DEFAULT`,
		`COMMENT ON COLUMN "app"."items"."amount" IS 'in cents'`,
		`ALTER TABLE "app"."items" ADD COLUMN "tags" text[] DEFAULT '{}'`,
		`CREATE INDEX "items_tags" ON "app"."items" USING gin ("tags")`,
	} {
		if !strings.Contains(joined, want) {
			t.Errorf("missing %q in:\n%s", want, joined)
		}
	}
	if strings.Contains(joined, "items_pkey") || strings.Contains(joined, `"id"`) && strings.Contains(joined, `ALTER COLUMN "id"`) {
		t.Errorf("unchanged key touched:\n%s", joined)
	}
}

func TestPGAutoIncrementBecomesIdentity(t *testing.T) {
	c := &conn{}
	stmts, err := c.CreateTableSQL(driver.TableDef{
		Ref:        driver.ObjectRef{Schema: "app", Name: "t"},
		Columns:    []driver.ColumnDef{{Column: driver.Column{Name: "id", Type: "bigint", AutoIncrement: true}}},
		PrimaryKey: []string{"id"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(stmts[0], `"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`) {
		t.Errorf("got %s", stmts[0])
	}
}
