package oracle

import (
	"errors"
	"fmt"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"rowsmith/internal/driver"
)

// DDL generation (driver.DDLGenerator). Statements are plain SQL without
// trailing semicolons and nothing here touches the server. Oracle commits
// every DDL statement on its own, so a script that fails halfway stays half
// applied: whatever Oracle is known to refuse is rejected here, before
// anything runs. Columns cannot be reordered; new ones go at the end.

var design = driver.TableDesign{
	Columns: true, AutoIncrement: true, ColumnComments: true, TableComment: true, Generated: true, GeneratedVirtual: true,
	Checks: true, PrimaryKey: true, ForeignKeys: true, Indexes: true,
	IndexTypes: []string{"btree", "bitmap", "btree (reverse)"},
	FKActions:  []string{"NO ACTION", "CASCADE", "SET NULL"},
	Note: "Oracle cannot move existing columns; new columns are added at the end. Identity (auto-increment) can only be set " +
		"when a column is created, generated columns are always virtual, and foreign keys have no ON UPDATE rule.",
}

// autoIdentity is what Column.AutoIncrement asks for: numbering that also
// fills in explicit NULLs, the closest match to other engines.
const autoIdentity = "GENERATED BY DEFAULT ON NULL AS IDENTITY"

func (c *conn) tableName(r driver.ObjectRef) string {
	if s := c.schema(r.Schema); s != "" {
		return qualify(s, r.Name)
	}
	return quote(r.Name)
}

// objectName qualifies a schema object (index, view...) like tableName.
func (c *conn) objectName(schema, name string) string {
	return c.tableName(driver.ObjectRef{Schema: schema, Name: name})
}

func quoteList(cols []string) string {
	q := make([]string, len(cols))
	for i, c := range cols {
		q[i] = quote(c)
	}
	return strings.Join(q, ", ")
}

func deref(s *string) string {
	if s == nil {
		return ""
	}
	return strings.TrimSpace(*s)
}

func hasPrefixFold(s, prefix string) bool {
	return len(s) >= len(prefix) && strings.EqualFold(s[:len(prefix)], prefix)
}

// isIdentityClause reports defaults that describe an identity column.
func isIdentityClause(s string) bool { return hasPrefixFold(strings.TrimSpace(s), "GENERATED ") }

// isOnNull reports DEFAULT ON NULL expressions ("ON NULL 0"), which also
// make the column NOT NULL.
func isOnNull(s string) bool { return hasPrefixFold(strings.TrimSpace(s), "ON NULL ") }

// plainDefault is a column's DEFAULT expression; identity clauses and NULL
// are not defaults.
func plainDefault(s *string) string {
	d := deref(s)
	if isIdentityClause(d) || strings.EqualFold(d, "NULL") {
		return ""
	}
	return d
}

// identityClause is the identity a column asks for, or "".
func identityClause(col driver.Column) string {
	if d := deref(col.Default); isIdentityClause(d) {
		return d
	}
	if col.AutoIncrement {
		return autoIdentity
	}
	return ""
}

// sameText compares SQL fragments ignoring case and spacing.
func sameText(a, b string) bool {
	norm := func(s string) string {
		s = strings.Join(strings.Fields(strings.ToUpper(s)), " ")
		for _, p := range []string{"(", ")", ","} {
			s = strings.ReplaceAll(strings.ReplaceAll(s, " "+p, p), p+" ", p)
		}
		return s
	}
	return norm(a) == norm(b)
}

// errOnUpdate refuses MySQL's ON UPDATE column clause.
func errOnUpdate(col driver.Column) error {
	if strings.TrimSpace(col.OnUpdate) != "" {
		return fmt.Errorf("column %s: Oracle has no ON UPDATE clause for columns; use a trigger", col.Name)
	}
	return nil
}

func colDef(col driver.Column) (string, error) {
	if strings.TrimSpace(col.Name) == "" {
		return "", errors.New("every column needs a name")
	}
	if err := errOnUpdate(col); err != nil {
		return "", err
	}
	typ := strings.TrimSpace(col.Type)
	s := quote(col.Name)
	if col.Generated != "" {
		if col.GeneratedStored {
			return "", fmt.Errorf("column %s: Oracle generated columns are always virtual, not stored", col.Name)
		}
		if col.AutoIncrement {
			return "", fmt.Errorf("column %s cannot be both generated and an identity column", col.Name)
		}
		if typ != "" {
			s += " " + typ
		}
		s += " GENERATED ALWAYS AS (" + col.Generated + ") VIRTUAL"
	} else {
		if typ == "" {
			return "", fmt.Errorf("column %s needs a type", col.Name)
		}
		s += " " + typ
		if id := identityClause(col); id != "" {
			s += " " + id
		} else if d := plainDefault(col.Default); d != "" {
			s += " DEFAULT " + d
		}
	}
	if !col.Nullable {
		s += " NOT NULL"
	}
	return s, nil
}

// keyPart renders one index key: a column, or an expression kept verbatim
// (function-based index), e.g. UPPER("NAME") or (PRICE * QTY).
func keyPart(key string, desc bool, columns map[string]bool) string {
	p := key
	if columns[key] || !isExpression(key) {
		p = quote(key)
	}
	if desc {
		p += " DESC"
	}
	return p
}

// indexType maps Index.Type (as Describe reports it) to the kinds DDL knows.
func indexType(t string) string {
	switch s := strings.ToLower(strings.TrimSpace(t)); s {
	case "", "btree", "normal":
		return "btree"
	case "normal/rev", "reverse":
		return "btree (reverse)"
	default:
		return s
	}
}

// indexKey identifies an index definition; keys are passed already renamed.
func indexKey(ix driver.Index, keys []string) string {
	parts := make([]string, len(keys))
	for i, k := range keys {
		parts[i] = keyPart(k, i < len(ix.Desc) && ix.Desc[i], nil)
	}
	return fmt.Sprintf("%v|%s|%s|%s", ix.Unique, indexType(ix.Type), strings.Join(parts, ","), strings.TrimSpace(ix.Where))
}

func label(kind, name string, cols []string) string {
	if name != "" {
		return kind + " " + name
	}
	return kind + " on (" + strings.Join(cols, ", ") + ")"
}

func (c *conn) createIndex(table, schema string, ix driver.Index, keys []string, columns map[string]bool) (string, error) {
	if strings.TrimSpace(ix.Name) == "" {
		return "", errors.New("every index needs a name")
	}
	if len(keys) == 0 {
		return "", fmt.Errorf("index %s needs at least one column", ix.Name)
	}
	if strings.TrimSpace(ix.Where) != "" {
		return "", fmt.Errorf("index %s: Oracle has no partial indexes", ix.Name)
	}
	kw, suffix := "INDEX", ""
	switch typ := indexType(ix.Type); typ {
	case "btree":
	case "btree (reverse)":
		suffix = " REVERSE"
	case "bitmap":
		if ix.Unique {
			return "", fmt.Errorf("index %s: a bitmap index cannot be unique", ix.Name)
		}
		kw = "BITMAP INDEX"
	default:
		return "", fmt.Errorf("index %s is a %s index, which the structure editor cannot create; use the SQL console", ix.Name, typ)
	}
	if ix.Unique {
		kw = "UNIQUE INDEX"
	}
	parts := make([]string, len(keys))
	for i, k := range keys {
		parts[i] = keyPart(k, i < len(ix.Desc) && ix.Desc[i], columns)
	}
	return "CREATE " + kw + " " + c.objectName(schema, ix.Name) + " ON " + table + " (" + strings.Join(parts, ", ") + ")" + suffix, nil
}

var constraintDef = regexp.MustCompile(`^ALTER TABLE "(?:[^"]|"")+"\."(?:[^"]|"")+" ADD CONSTRAINT "((?:[^"]|"")+)" (UNIQUE|PRIMARY KEY) \(`)

// constraintOf returns the constraint an index enforces, as Describe records
// it in the index definition (constraintDDL).
func constraintOf(ix driver.Index) (string, bool) {
	m := constraintDef.FindStringSubmatch(ix.Definition)
	if m == nil {
		return "", false
	}
	return strings.ReplaceAll(m[1], `""`, `"`), true
}

// deleteRule validates a foreign key's rules and returns the ON DELETE
// clause to emit ("" for NO ACTION).
func deleteRule(fk driver.ForeignKey) (string, error) {
	if u := strings.ToUpper(strings.TrimSpace(fk.OnUpdate)); u != "" && u != "NO ACTION" {
		return "", fmt.Errorf("%s: Oracle foreign keys have no ON UPDATE rule", label("foreign key", fk.Name, fk.Columns))
	}
	switch d := strings.Join(strings.Fields(strings.ToUpper(fk.OnDelete)), " "); d {
	case "", "NO ACTION":
		return "", nil
	case "CASCADE", "SET NULL":
		return d, nil
	default:
		return "", fmt.Errorf("%s: Oracle supports ON DELETE CASCADE or SET NULL only, not %s", label("foreign key", fk.Name, fk.Columns), d)
	}
}

// fkClause renders a foreign key; the referenced table defaults to schema.
func (c *conn) fkClause(fk driver.ForeignKey, schema string) (string, error) {
	if len(fk.Columns) == 0 || len(fk.Columns) != len(fk.RefColumns) {
		return "", fmt.Errorf("%s needs the same number of columns on both sides", label("foreign key", fk.Name, fk.Columns))
	}
	if fk.RefTable.Name == "" {
		return "", fmt.Errorf("%s needs a referenced table", label("foreign key", fk.Name, fk.Columns))
	}
	rule, err := deleteRule(fk)
	if err != nil {
		return "", err
	}
	s := ""
	if fk.Name != "" {
		s = "CONSTRAINT " + quote(fk.Name) + " "
	}
	rs := fk.RefTable.Schema
	if rs == "" {
		rs = schema
	}
	s += "FOREIGN KEY (" + quoteList(fk.Columns) + ") REFERENCES " + c.objectName(rs, fk.RefTable.Name) + " (" + quoteList(fk.RefColumns) + ")"
	if rule != "" {
		s += " ON DELETE " + rule
	}
	return s, nil
}

// sameFK compares foreign keys as AlterTableSQL normalizes them.
func sameFK(a, b driver.ForeignKey) bool {
	rule := func(r string) string {
		r = strings.ToUpper(strings.TrimSpace(r))
		if r == "" {
			return "NO ACTION"
		}
		return r
	}
	return slices.Equal(a.Columns, b.Columns) && slices.Equal(a.RefColumns, b.RefColumns) && a.RefTable.Name == b.RefTable.Name &&
		a.RefTable.Schema == b.RefTable.Schema && rule(a.OnDelete) == rule(b.OnDelete) && rule(a.OnUpdate) == rule(b.OnUpdate)
}

func checkClause(ch driver.Check) (string, error) {
	if strings.TrimSpace(ch.Expression) == "" {
		return "", fmt.Errorf("%s needs an expression", label("check", ch.Name, nil))
	}
	s := "CHECK (" + strings.TrimSpace(ch.Expression) + ")"
	if ch.Name != "" {
		s = "CONSTRAINT " + quote(ch.Name) + " " + s
	}
	return s, nil
}

// maxIdent is the longest identifier the server accepts, in bytes.
func (c *conn) maxIdent() int {
	parts := strings.SplitN(c.version, ".", 3)
	major, _ := strconv.Atoi(parts[0])
	minor := 0
	if len(parts) > 1 {
		minor, _ = strconv.Atoi(parts[1])
	}
	if major > 0 && (major < 12 || major == 12 && minor < 2) {
		return 30
	}
	return 128
}

// pkName names a new primary key: an existing user-given name, else
// TABLE_PK as Oracle's own tools do, else (too long) a system name.
func (c *conn) pkName(table string, indexes []driver.Index) string {
	for _, ix := range indexes {
		if !ix.Primary {
			continue
		}
		name := ix.Name
		if cn, ok := constraintOf(ix); ok {
			name = cn
		}
		if name != "" && !systemName(name) {
			return name
		}
	}
	if n := table + "_PK"; len(n) <= c.maxIdent() {
		return n
	}
	return ""
}

// systemName reports names Oracle generated (SYS_C00123), which are not
// given again when a key is re-created.
func systemName(n string) bool { return strings.HasPrefix(n, "SYS_") }

func pkClause(name string, cols []string) string {
	s := "PRIMARY KEY (" + quoteList(cols) + ")"
	if name != "" {
		s = "CONSTRAINT " + quote(name) + " " + s
	}
	return s
}

func (c *conn) CreateTableSQL(def driver.TableDef) ([]string, error) {
	if strings.TrimSpace(def.Ref.Name) == "" {
		return nil, errors.New("give the table a name")
	}
	if len(def.Columns) == 0 {
		return nil, errors.New("a table needs at least one column")
	}
	schema := c.schema(def.Ref.Schema)
	table := c.tableName(def.Ref)
	var lines []string
	columns := map[string]bool{}
	for _, col := range def.Columns {
		if columns[col.Name] {
			return nil, fmt.Errorf("column %s is listed twice", col.Name)
		}
		columns[col.Name] = true
		d, err := colDef(col.Column)
		if err != nil {
			return nil, err
		}
		lines = append(lines, d)
	}
	if len(def.PrimaryKey) > 0 {
		lines = append(lines, pkClause(c.pkName(def.Ref.Name, def.Indexes), def.PrimaryKey))
	}
	for _, ch := range def.Checks {
		s, err := checkClause(ch)
		if err != nil {
			return nil, err
		}
		lines = append(lines, s)
	}
	for _, fk := range def.ForeignKeys {
		s, err := c.fkClause(fk, schema)
		if err != nil {
			return nil, err
		}
		lines = append(lines, s)
	}
	out := []string{"CREATE TABLE " + table + " (\n  " + strings.Join(lines, ",\n  ") + "\n)"}
	for _, ix := range def.Indexes {
		if ix.Primary {
			continue
		}
		s, err := c.createIndex(table, schema, ix, ix.Columns, columns)
		if err != nil {
			return nil, err
		}
		out = append(out, s)
	}
	if def.Comment != "" {
		out = append(out, "COMMENT ON TABLE "+table+" IS "+literal(def.Comment))
	}
	for _, col := range def.Columns {
		if col.Comment != "" {
			out = append(out, "COMMENT ON COLUMN "+table+"."+quote(col.Name)+" IS "+literal(col.Comment))
		}
	}
	return out, nil
}

// renames tracks the column renames of one change. Oracle carries a renamed
// column into its indexes, keys, checks and virtual column expressions, so
// current definitions are read with the new names, and a submitted one may
// still use an old name, before the two are compared.
type renames struct {
	to    map[string]string // current name -> new name
	after map[string]bool   // column names after the change
}

func (r renames) name(n string, current bool) string {
	if x, ok := r.to[n]; ok && (current || !r.after[n]) {
		return x
	}
	return n
}

// isExpression reports index keys that are expressions, not column names.
func isExpression(key string) bool { return strings.ContainsAny(key, `("`) }

func (r renames) keys(names []string, current bool) []string {
	out := make([]string, len(names))
	for i, n := range names {
		if isExpression(n) {
			out[i] = r.expr(n, current)
		} else {
			out[i] = r.name(n, current)
		}
	}
	return out
}

// expr renames the quoted column names of an expression (Oracle stores them
// quoted), leaving string literals alone.
func (r renames) expr(s string, current bool) string {
	s = strings.TrimSpace(s)
	if len(r.to) == 0 {
		return s
	}
	var b strings.Builder
	for i := 0; i < len(s); {
		switch s[i] {
		case '\'':
			j := i + 1
			for j < len(s) {
				if s[j] == '\'' {
					if j+1 < len(s) && s[j+1] == '\'' {
						j += 2 // escaped quote
						continue
					}
					break
				}
				j++
			}
			j = min(j+1, len(s))
			b.WriteString(s[i:j])
			i = j
		case '"':
			j := strings.IndexByte(s[i+1:], '"')
			if j < 0 {
				b.WriteString(s[i:])
				i = len(s)
				continue
			}
			b.WriteString(quote(r.name(s[i+1:i+1+j], current)))
			i += j + 2
		default:
			b.WriteByte(s[i])
			i++
		}
	}
	return b.String()
}

// AlterTableSQL diffs the current table against the desired definition.
// Columns are matched by OriginalName; unmatched current columns are dropped.
// Keys, indexes and constraints are matched by name and re-created when they
// changed.
func (c *conn) AlterTableSQL(from *driver.Table, to driver.TableDef) ([]string, error) {
	if from == nil {
		return nil, errors.New("current table definition is missing")
	}
	if from.Kind != "" && from.Kind != "table" {
		return nil, fmt.Errorf("%s is a %s, not a table", from.Ref.Name, kindLabel(from.Kind))
	}
	schema := c.schema(from.Ref.Schema)
	target := c.tableName(from.Ref)
	alter := func(clause string) string { return "ALTER TABLE " + target + " " + clause }

	current := map[string]driver.Column{}
	for _, col := range from.Columns {
		current[col.Name] = col
	}
	kept := map[string]bool{} // current columns that stay
	r := renames{to: map[string]string{}, after: map[string]bool{}}
	for _, col := range to.Columns {
		if strings.TrimSpace(col.Name) == "" {
			return nil, errors.New("every column needs a name")
		}
		if r.after[col.Name] {
			return nil, fmt.Errorf("column %s is listed twice", col.Name)
		}
		r.after[col.Name] = true
		if col.OriginalName == "" {
			continue
		}
		if _, ok := current[col.OriginalName]; !ok {
			return nil, fmt.Errorf("column %s no longer exists; reload the structure", col.OriginalName)
		}
		if kept[col.OriginalName] {
			return nil, fmt.Errorf("column %s is listed twice", col.OriginalName)
		}
		kept[col.OriginalName] = true
		if col.Name != col.OriginalName {
			r.to[col.OriginalName] = col.Name
		}
	}

	// Oracle will not change a column's type under a function-based index
	// (ORA-30556) nor a virtual column's expression under any index
	// (ORA-54022), so such indexes are dropped and re-created around the
	// change. Nor will it retype a column a virtual column uses (ORA-54031).
	retyped, recomputed := map[string]bool{}, map[string]bool{}
	for _, col := range to.Columns {
		if col.OriginalName == "" {
			continue
		}
		old := current[col.OriginalName]
		typ := strings.TrimSpace(col.Type)
		typeChanged := typ != "" && !sameText(typ, old.Type)
		switch {
		case old.Generated != "" && col.Generated != "":
			recomputed[old.Name] = typeChanged || r.expr(old.Generated, true) != r.expr(col.Generated, false)
		case old.Generated == "" && col.Generated == "":
			retyped[old.Name] = typeChanged
		}
	}
	for _, v := range from.Columns {
		if v.Generated == "" || !kept[v.Name] {
			continue
		}
		for _, col := range from.Columns {
			if retyped[col.Name] && strings.Contains(v.Generated, quote(col.Name)) {
				return nil, fmt.Errorf("column %s is used by virtual column %s, so Oracle cannot change its type; drop %s first", col.Name, v.Name, v.Name)
			}
		}
	}
	rebuild := map[string]bool{}
	for _, ix := range from.Indexes {
		for _, k := range ix.Columns {
			if !isExpression(k) {
				rebuild[ix.Name] = rebuild[ix.Name] || recomputed[k]
				continue
			}
			for _, col := range from.Columns {
				if (retyped[col.Name] || recomputed[col.Name]) && strings.Contains(k, quote(col.Name)) {
					rebuild[ix.Name] = true
				}
			}
		}
	}

	var out []string

	// Foreign keys are read with renamed columns and the referenced table
	// resolved; a reference to the table itself follows its renames too.
	fkNorm := func(fk driver.ForeignKey, current bool) driver.ForeignKey {
		n := fk
		n.Columns = r.keys(fk.Columns, current)
		if n.RefTable.Schema == "" {
			n.RefTable.Schema = schema
		}
		if n.RefTable.Schema == schema && (n.RefTable.Name == from.Ref.Name || !current && n.RefTable.Name == to.Ref.Name) {
			n.RefTable.Name = from.Ref.Name // renamed last
			n.RefColumns = r.keys(fk.RefColumns, current)
		}
		return n
	}
	// Foreign keys go first: they depend on the keys and columns changed below.
	toFK := map[string]driver.ForeignKey{}
	for _, fk := range to.ForeignKeys {
		if fk.Name != "" {
			toFK[fk.Name] = fkNorm(fk, false)
		}
	}
	fromFK := map[string]driver.ForeignKey{}
	droppedFK := map[string]bool{}
	for _, fk := range from.ForeignKeys {
		fromFK[fk.Name] = fkNorm(fk, true)
		if n, ok := toFK[fk.Name]; !ok || !sameFK(fromFK[fk.Name], n) {
			out = append(out, alter("DROP CONSTRAINT "+quote(fk.Name)))
			droppedFK[fk.Name] = true
		}
	}
	// Oracle refuses to drop a key or column that foreign keys of other
	// tables (or this one's, when they stay) reference: ORA-02273 and
	// ORA-12992, after earlier statements already ran.
	var incoming []driver.ForeignKey
	for _, fk := range from.Referenced {
		self := fk.Table != nil && fk.Table.Name == from.Ref.Name && (fk.Table.Schema == "" || fk.Table.Schema == from.Ref.Schema)
		if !self || !droppedFK[fk.Name] {
			incoming = append(incoming, fk)
		}
	}
	inUse := func(what string, fk driver.ForeignKey) error {
		src := fk.Name
		if fk.Table != nil {
			src = fk.Table.Name + "." + fk.Name
		}
		return fmt.Errorf("%s is referenced by foreign key %s; drop that foreign key first", what, src)
	}
	keyInUse := func(what string, cols []string) error {
		for _, fk := range incoming {
			a, b := slices.Clone(fk.RefColumns), slices.Clone(cols)
			slices.Sort(a)
			slices.Sort(b)
			if slices.Equal(a, b) {
				return inUse(what, fk)
			}
		}
		return nil
	}

	toCk := map[string]driver.Check{}
	for _, ch := range to.Checks {
		if ch.Name != "" {
			toCk[ch.Name] = ch
		}
	}
	fromCk := map[string]driver.Check{}
	for _, ch := range from.Checks {
		fromCk[ch.Name] = ch
		if n, ok := toCk[ch.Name]; !ok || r.expr(n.Expression, false) != r.expr(ch.Expression, true) {
			out = append(out, alter("DROP CONSTRAINT "+quote(ch.Name)))
		}
	}

	fromPK, toPK := r.keys(from.PrimaryKey, true), r.keys(to.PrimaryKey, false)
	pkChanged := !slices.Equal(fromPK, toPK)
	if pkChanged && len(from.PrimaryKey) > 0 {
		if err := keyInUse("the primary key", from.PrimaryKey); err != nil {
			return nil, err
		}
		out = append(out, alter("DROP PRIMARY KEY DROP INDEX"))
	}

	toIx := map[string]driver.Index{}
	for _, ix := range to.Indexes {
		if !ix.Primary {
			toIx[ix.Name] = ix
		}
	}
	fromIx := map[string]driver.Index{}
	for _, ix := range from.Indexes {
		if ix.Primary {
			continue
		}
		fromIx[ix.Name] = ix
		if n, ok := toIx[ix.Name]; ok && !rebuild[ix.Name] && indexKey(n, r.keys(n.Columns, false)) == indexKey(ix, r.keys(ix.Columns, true)) {
			continue
		}
		if cn, ok := constraintOf(ix); ok {
			if err := keyInUse("unique key "+cn, ix.Columns); err != nil {
				return nil, err
			}
			out = append(out, alter("DROP CONSTRAINT "+quote(cn)+" DROP INDEX"))
		} else {
			out = append(out, "DROP INDEX "+c.objectName(schema, ix.Name))
		}
	}

	for _, col := range from.Columns {
		if kept[col.Name] {
			continue
		}
		for _, fk := range incoming {
			if slices.Contains(fk.RefColumns, col.Name) {
				return nil, inUse("column "+col.Name, fk)
			}
		}
		out = append(out, alter("DROP COLUMN "+quote(col.Name)))
	}
	for _, col := range to.Columns {
		if col.OriginalName == "" {
			d, err := colDef(col.Column)
			if err != nil {
				return nil, err
			}
			out = append(out, alter("ADD ("+d+")"))
			if col.Comment != "" {
				out = append(out, "COMMENT ON COLUMN "+target+"."+quote(col.Name)+" IS "+literal(col.Comment))
			}
			continue
		}
		old := current[col.OriginalName]
		if col.Nullable && !old.Nullable && !pkChanged && slices.Contains(toPK, col.Name) {
			return nil, fmt.Errorf("column %s is part of the primary key, which keeps it NOT NULL", col.Name)
		}
		if col.Name != old.Name {
			out = append(out, alter("RENAME COLUMN "+quote(old.Name)+" TO "+quote(col.Name)))
		}
		was, want := old, col.Column
		was.Generated, want.Generated = r.expr(old.Generated, true), r.expr(col.Generated, false)
		stmts, err := modifyColumn(alter, was, want)
		if err != nil {
			return nil, err
		}
		out = append(out, stmts...)
		if col.Comment != old.Comment {
			out = append(out, "COMMENT ON COLUMN "+target+"."+quote(col.Name)+" IS "+literal(col.Comment))
		}
	}

	if pkChanged && len(to.PrimaryKey) > 0 {
		name := to.Ref.Name
		if name == "" {
			name = from.Ref.Name
		}
		out = append(out, alter("ADD "+pkClause(c.pkName(name, from.Indexes), toPK)))
	}
	for _, ix := range to.Indexes {
		if ix.Primary {
			continue
		}
		keys := r.keys(ix.Columns, false)
		old, ok := fromIx[ix.Name]
		if ok && !rebuild[ix.Name] && indexKey(ix, keys) == indexKey(old, r.keys(old.Columns, true)) {
			continue
		}
		// A changed unique constraint stays a constraint when it can.
		if cn, isCons := constraintOf(old); ok && isCons && ix.Unique && indexType(ix.Type) == "btree" && !slices.Contains(ix.Desc, true) &&
			!slices.ContainsFunc(keys, func(k string) bool { return !r.after[k] }) {
			clause := "UNIQUE (" + quoteList(keys) + ")"
			if !systemName(cn) {
				clause = "CONSTRAINT " + quote(cn) + " " + clause
			}
			out = append(out, alter("ADD "+clause))
			continue
		}
		s, err := c.createIndex(target, schema, ix, keys, r.after)
		if err != nil {
			return nil, err
		}
		out = append(out, s)
	}
	for _, ch := range to.Checks {
		expr := r.expr(ch.Expression, false)
		if old, ok := fromCk[ch.Name]; ok && ch.Name != "" && r.expr(old.Expression, true) == expr {
			continue
		}
		s, err := checkClause(driver.Check{Name: ch.Name, Expression: expr})
		if err != nil {
			return nil, err
		}
		out = append(out, alter("ADD "+s))
	}
	for _, fk := range to.ForeignKeys {
		fk = fkNorm(fk, false)
		if old, ok := fromFK[fk.Name]; ok && fk.Name != "" && sameFK(old, fk) {
			continue
		}
		s, err := c.fkClause(fk, schema)
		if err != nil {
			return nil, err
		}
		out = append(out, alter("ADD "+s))
	}
	if to.Comment != from.Comment {
		out = append(out, "COMMENT ON TABLE "+target+" IS "+literal(to.Comment))
	}
	if to.Ref.Name != "" && to.Ref.Name != from.Ref.Name {
		out = append(out, alter("RENAME TO "+quote(to.Ref.Name)))
	}
	return out, nil
}

// modifyColumn changes an existing column (already renamed) to match col.
// Oracle rejects NOT NULL on a NOT NULL column (ORA-01442) and NULL on a
// nullable one (ORA-01451), so nullability is only sent when it changes.
func modifyColumn(alter func(string) string, old, col driver.Column) ([]string, error) {
	qn := quote(col.Name)
	modify := func(parts ...string) string { return alter("MODIFY (" + qn + " " + strings.Join(parts, " ") + ")") }
	nullability := func(nullable bool) string {
		if nullable {
			return "NULL"
		}
		return "NOT NULL"
	}
	typ := strings.TrimSpace(col.Type)
	var out []string
	if err := errOnUpdate(col); err != nil {
		return nil, err
	}
	if (old.Generated != "") != (col.Generated != "") {
		return nil, fmt.Errorf("Oracle cannot turn column %s into or out of a generated column; drop it and add a new one", old.Name)
	}
	if col.Generated != "" {
		if col.GeneratedStored {
			return nil, fmt.Errorf("column %s: Oracle generated columns are always virtual, not stored", col.Name)
		}
		typeChanged := typ != "" && !sameText(typ, old.Type)
		if typeChanged || strings.TrimSpace(col.Generated) != strings.TrimSpace(old.Generated) {
			parts := []string{"AS (" + col.Generated + ")"}
			if typeChanged {
				parts = append([]string{typ}, parts...)
			}
			out = append(out, modify(parts...))
		}
		if col.Nullable != old.Nullable {
			out = append(out, modify(nullability(col.Nullable)))
		}
		return out, nil
	}

	if typ == "" {
		return nil, fmt.Errorf("column %s needs a type", col.Name)
	}
	// A stale identity clause left in the default of a column whose
	// auto-increment was switched off does not keep the identity.
	wasID := old.AutoIncrement || isIdentityClause(deref(old.Default))
	wantID := col.AutoIncrement || isIdentityClause(deref(col.Default)) && !old.AutoIncrement
	switch {
	case wantID && !wasID:
		return nil, fmt.Errorf("Oracle cannot make existing column %s an identity column; add a new column instead", old.Name)
	case wasID && !wantID:
		out = append(out, modify("DROP IDENTITY"))
	case wasID:
		if d := deref(col.Default); isIdentityClause(d) && !sameText(d, deref(old.Default)) {
			out = append(out, modify(d))
		}
	}

	var parts []string
	if !sameText(typ, old.Type) {
		parts = append(parts, typ)
	}
	if wantID {
		// Identity columns are NOT NULL whatever the definition says.
		if len(parts) > 0 {
			out = append(out, modify(parts...))
		}
		return out, nil
	}
	oldNullable := old.Nullable
	oldDef, newDef := plainDefault(old.Default), plainDefault(col.Default)
	if oldDef != newDef {
		d := "DEFAULT NULL"
		if newDef != "" {
			d = "DEFAULT " + newDef
		}
		if isOnNull(oldDef) && !isOnNull(newDef) {
			// Leaving DEFAULT ON NULL also drops the NOT NULL it implies.
			out = append(out, modify(append(parts, d)...))
			parts, oldNullable = nil, true
		} else {
			parts = append(parts, d)
		}
	}
	if col.Nullable != oldNullable {
		switch {
		case isOnNull(newDef) && col.Nullable:
			return nil, fmt.Errorf("column %s has DEFAULT ON NULL, which keeps it NOT NULL", col.Name)
		case isOnNull(newDef):
			// DEFAULT ON NULL makes the column NOT NULL by itself.
		default:
			parts = append(parts, nullability(col.Nullable))
		}
	}
	if len(parts) > 0 {
		out = append(out, modify(parts...))
	}
	return out, nil
}

var dropKeyword = map[string]string{
	"table": "TABLE", "view": "VIEW", "materialized_view": "MATERIALIZED VIEW", "sequence": "SEQUENCE", "synonym": "SYNONYM",
	"package": "PACKAGE", "package_body": "PACKAGE BODY", "procedure": "PROCEDURE", "function": "FUNCTION", "trigger": "TRIGGER",
	"type": "TYPE", "type_body": "TYPE BODY", "index": "INDEX",
}

func kindLabel(kind string) string { return strings.ReplaceAll(kind, "_", " ") }

// DropObjectSQL drops an object. With cascade, a table or view also loses
// the foreign keys that reference it and a type is dropped even while
// other objects depend on it. Dropped tables go to the recycle bin.
func (c *conn) DropObjectSQL(ref driver.ObjectRef, cascade bool) ([]string, error) {
	kw, ok := dropKeyword[ref.Kind]
	if !ok {
		return nil, fmt.Errorf("cannot drop objects of kind %q", ref.Kind)
	}
	if strings.TrimSpace(ref.Name) == "" {
		return nil, errors.New("choose an object to drop")
	}
	s := "DROP " + kw + " " + c.tableName(ref)
	if cascade {
		switch ref.Kind {
		case "table", "view":
			s += " CASCADE CONSTRAINTS"
		case "type":
			s += " FORCE"
		}
	}
	return []string{s}, nil
}

func (c *conn) TruncateSQL(ref driver.ObjectRef) ([]string, error) {
	if ref.Kind != "" && ref.Kind != "table" {
		return nil, fmt.Errorf("only tables can be emptied, not a %s", kindLabel(ref.Kind))
	}
	return []string{"TRUNCATE TABLE " + c.tableName(ref)}, nil
}

func (c *conn) RenameObjectSQL(ref driver.ObjectRef, newName string) ([]string, error) {
	if strings.TrimSpace(newName) == "" {
		return nil, errors.New("enter a new name")
	}
	switch ref.Kind {
	case "", "table":
		return []string{"ALTER TABLE " + c.tableName(ref) + " RENAME TO " + quote(newName)}, nil
	case "index", "trigger":
		return []string{"ALTER " + dropKeyword[ref.Kind] + " " + c.tableName(ref) + " RENAME TO " + quote(newName)}, nil
	case "view", "sequence", "synonym":
		// RENAME only works on objects in the session user's own schema.
		if ref.Schema != "" && ref.Schema != c.user {
			return nil, fmt.Errorf("Oracle can only rename a %s in your own schema (%s)", ref.Kind, c.user)
		}
		return []string{"RENAME " + quote(ref.Name) + " TO " + quote(newName)}, nil
	case "materialized_view", "procedure", "function", "package", "package_body", "type", "type_body":
		return nil, fmt.Errorf("Oracle cannot rename a %s; recreate it under the new name", kindLabel(ref.Kind))
	}
	return nil, fmt.Errorf("renaming a %s is not supported", kindLabel(ref.Kind))
}

var errDatabases = errors.New("Oracle pluggable databases are created and dropped by a DBA outside Rowsmith")

func (c *conn) CreateDatabaseSQL(string, map[string]string) ([]string, error) {
	return nil, errDatabases
}
func (c *conn) DropDatabaseSQL(string) ([]string, error) { return nil, errDatabases }
