package oracle

import (
	"encoding/json"
	"strings"
	"testing"

	"rowsmith/internal/driver"
)

func strp(s string) *string { return &s }

// tableDef builds the definition the structure editor submits for an
// unchanged table: Describe's result as JSON, every column linked by name.
func tableDef(t *driver.Table) driver.TableDef {
	var cp driver.Table
	b, _ := json.Marshal(t)
	_ = json.Unmarshal(b, &cp)
	def := driver.TableDef{Ref: cp.Ref, PrimaryKey: cp.PrimaryKey, Indexes: cp.Indexes, ForeignKeys: cp.ForeignKeys, Checks: cp.Checks,
		Comment: cp.Comment, Options: cp.Options}
	for _, col := range cp.Columns {
		def.Columns = append(def.Columns, driver.ColumnDef{Column: col, OriginalName: col.Name})
	}
	return def
}

// describedCustomers is RS_CUSTOMERS as describe.go reports it, with the
// artefacts a round trip must survive: a system-named primary key, a unique
// constraint shown as its index, an identity column, a virtual column and
// a function-based index.
func describedCustomers() *driver.Table {
	ident := "GENERATED BY DEFAULT AS IDENTITY"
	tbl := &driver.Table{
		Ref: driver.ObjectRef{Schema: "SHOP", Name: "RS_CUSTOMERS", Kind: "table"}, Kind: "table", Comment: "Customers",
		Options: map[string]string{"tablespace": "USERS"},
		Columns: []driver.Column{
			{Name: "ID", Type: "NUMBER(10)", BaseType: "number", Kind: driver.KindInt, Default: &ident, AutoIncrement: true, PrimaryKey: true},
			{Name: "NAME", Type: "VARCHAR2(100 CHAR)", BaseType: "varchar2", Kind: driver.KindString},
			{Name: "EMAIL", Type: "VARCHAR2(200 BYTE)", BaseType: "varchar2", Kind: driver.KindString, Nullable: true, Comment: "Login email"},
			{Name: "CREATED", Type: "DATE", BaseType: "date", Kind: driver.KindDateTime, Nullable: true, Default: strp("SYSDATE")},
			{Name: "BALANCE", Type: "NUMBER(12,2)", BaseType: "number", Kind: driver.KindDecimal, Nullable: true, Default: strp("0")},
			{Name: "STATUS", Type: "VARCHAR2(10 BYTE)", BaseType: "varchar2", Kind: driver.KindString, Default: strp("ON NULL 'new'")},
			{Name: "NAME_UPPER", Type: "VARCHAR2(400 CHAR)", BaseType: "varchar2", Kind: driver.KindString, Nullable: true, Generated: `UPPER("NAME")`},
		},
		PrimaryKey: []string{"ID"},
		Checks:     []driver.Check{{Name: "RS_CUSTOMERS_BALANCE_CK", Expression: "BALANCE >= 0"}, {Name: "SYS_C008431", Expression: "NAME <> 'x'"}},
		Referenced: []driver.ForeignKey{{Name: "RS_ORDERS_CUSTOMER_FK", Columns: []string{"CUSTOMER_ID"}, RefColumns: []string{"ID"}, OnDelete: "CASCADE",
			RefTable: driver.ObjectRef{Schema: "SHOP", Name: "RS_CUSTOMERS", Kind: "table"}, Table: &driver.ObjectRef{Schema: "SHOP", Name: "RS_ORDERS", Kind: "table"}}},
		Indexes: []driver.Index{
			{Name: "SYS_C008430", Columns: []string{"ID"}, Unique: true, Primary: true, Type: "btree", Desc: []bool{false}},
			{Name: "RS_CUSTOMERS_EMAIL_UK", Columns: []string{"EMAIL"}, Unique: true, Type: "btree", Desc: []bool{false}},
			{Name: "RS_CUSTOMERS_LOWER_IX", Columns: []string{`LOWER("EMAIL")`}, Type: "btree", Desc: []bool{false}},
			{Name: "RS_CUSTOMERS_REV_IX", Columns: []string{"CREATED", "BALANCE"}, Type: "btree (reverse)", Desc: []bool{false, true}},
		},
		RowKey: []string{"ID"}, RowKeyKind: "primary", Editable: true,
	}
	cols := map[string]bool{}
	for _, c := range tbl.Columns {
		cols[c.Name] = true
	}
	for i := range tbl.Indexes {
		tbl.Indexes[i].Definition = indexDDL("SHOP", tbl.Indexes[i], tbl, cols)
	}
	tbl.Indexes[0].Definition = constraintDDL(tbl, "SYS_C008430", "PRIMARY KEY", []string{"ID"})
	tbl.Indexes[1].Definition = constraintDDL(tbl, "RS_CUSTOMERS_EMAIL_UK", "UNIQUE", []string{"EMAIL"})
	return tbl
}

func describedOrders() *driver.Table {
	return &driver.Table{
		Ref: driver.ObjectRef{Schema: "SHOP", Name: "RS_ORDERS", Kind: "table"}, Kind: "table",
		Columns: []driver.Column{
			{Name: "ID", Type: "NUMBER(10)", PrimaryKey: true},
			{Name: "CUSTOMER_ID", Type: "NUMBER(10)"},
			{Name: "TOTAL", Type: "NUMBER(12,2)", Nullable: true},
			{Name: "REGION", Type: "VARCHAR2(10 BYTE)", Nullable: true},
		},
		PrimaryKey: []string{"ID"},
		ForeignKeys: []driver.ForeignKey{{Name: "RS_ORDERS_CUSTOMER_FK", Columns: []string{"CUSTOMER_ID"}, RefColumns: []string{"ID"}, OnDelete: "CASCADE",
			RefTable: driver.ObjectRef{Schema: "SHOP", Name: "RS_CUSTOMERS", Kind: "table"}, Table: &driver.ObjectRef{Schema: "SHOP", Name: "RS_ORDERS", Kind: "table"}}},
		Indexes: []driver.Index{
			{Name: "RS_ORDERS_PK", Columns: []string{"ID"}, Unique: true, Primary: true, Type: "btree", Desc: []bool{false},
				Definition: `ALTER TABLE "SHOP"."RS_ORDERS" ADD CONSTRAINT "RS_ORDERS_PK" PRIMARY KEY ("ID")`},
			{Name: "RS_ORDERS_REGION_BX", Columns: []string{"REGION"}, Type: "bitmap", Desc: []bool{false}},
		},
	}
}

func testConn() *conn { return &conn{user: "SHOP", version: "23.26.3.0.0"} }

func alterSQL(t *testing.T, from *driver.Table, to driver.TableDef) []string {
	t.Helper()
	stmts, err := testConn().AlterTableSQL(from, to)
	if err != nil {
		t.Fatal(err)
	}
	return stmts
}

func wantStatements(t *testing.T, got, want []string) {
	t.Helper()
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Errorf("statements\n got:\n%s\nwant:\n%s", strings.Join(got, "\n"), strings.Join(want, "\n"))
	}
}

func defColumn(def *driver.TableDef, name string) *driver.ColumnDef {
	for i := range def.Columns {
		if def.Columns[i].OriginalName == name {
			return &def.Columns[i]
		}
	}
	panic("no column " + name)
}

func TestCreateTableSQL(t *testing.T) {
	stmts, err := testConn().CreateTableSQL(driver.TableDef{
		Ref: driver.ObjectRef{Name: "NOTES"},
		Columns: []driver.ColumnDef{
			{Column: driver.Column{Name: "ID", Type: "NUMBER(19)", AutoIncrement: true}},
			{Column: driver.Column{Name: "BODY", Type: "CLOB", Nullable: true, Comment: "it's free text"}},
			{Column: driver.Column{Name: "CREATED", Type: "TIMESTAMP", Default: strp("SYSTIMESTAMP")}},
			{Column: driver.Column{Name: "RANK", Type: "NUMBER", Default: strp("ON NULL 0")}},
			{Column: driver.Column{Name: "AUTHOR_ID", Type: "NUMBER(10)", Nullable: true, Default: strp("")}},
			{Column: driver.Column{Name: "Title", Type: "VARCHAR2(100 CHAR)", Nullable: true}},
			{Column: driver.Column{Name: "TITLE_UPPER", Generated: `UPPER("Title")`, Nullable: true}},
		},
		PrimaryKey:  []string{"ID"},
		Checks:      []driver.Check{{Name: "NOTES_RANK_CK", Expression: "RANK >= 0"}, {Expression: "LENGTH(BODY) > 0"}},
		ForeignKeys: []driver.ForeignKey{{Name: "NOTES_AUTHOR_FK", Columns: []string{"AUTHOR_ID"}, RefTable: driver.ObjectRef{Name: "AUTHORS"}, RefColumns: []string{"ID"}, OnDelete: "SET NULL"}},
		Indexes: []driver.Index{
			{Name: "NOTES_CREATED_IX", Columns: []string{"CREATED", "Title"}, Desc: []bool{true}},
			{Name: "NOTES_TITLE_UK", Columns: []string{"(LOWER(\"Title\"))"}, Unique: true},
			{Name: "NOTES_RANK_BX", Columns: []string{"RANK"}, Type: "bitmap"},
		},
		Comment: "Team notes",
	})
	if err != nil {
		t.Fatal(err)
	}
	wantStatements(t, stmts, []string{
		`CREATE TABLE "SHOP"."NOTES" (
  "ID" NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
  "BODY" CLOB,
  "CREATED" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  "RANK" NUMBER DEFAULT ON NULL 0 NOT NULL,
  "AUTHOR_ID" NUMBER(10),
  "Title" VARCHAR2(100 CHAR),
  "TITLE_UPPER" GENERATED ALWAYS AS (UPPER("Title")) VIRTUAL,
  CONSTRAINT "NOTES_PK" PRIMARY KEY ("ID"),
  CONSTRAINT "NOTES_RANK_CK" CHECK (RANK >= 0),
  CHECK (LENGTH(BODY) > 0),
  CONSTRAINT "NOTES_AUTHOR_FK" FOREIGN KEY ("AUTHOR_ID") REFERENCES "SHOP"."AUTHORS" ("ID") ON DELETE SET NULL
)`,
		`CREATE INDEX "SHOP"."NOTES_CREATED_IX" ON "SHOP"."NOTES" ("CREATED" DESC, "Title")`,
		`CREATE UNIQUE INDEX "SHOP"."NOTES_TITLE_UK" ON "SHOP"."NOTES" ((LOWER("Title")))`,
		`CREATE BITMAP INDEX "SHOP"."NOTES_RANK_BX" ON "SHOP"."NOTES" ("RANK")`,
		`COMMENT ON TABLE "SHOP"."NOTES" IS 'Team notes'`,
		`COMMENT ON COLUMN "SHOP"."NOTES"."BODY" IS 'it''s free text'`,
	})

	// A primary key name that does not fit falls back to a system name.
	c := testConn()
	c.version = "12.1.0.2.0"
	stmts, err = c.CreateTableSQL(driver.TableDef{Ref: driver.ObjectRef{Schema: "HR", Name: strings.Repeat("T", 28)},
		Columns: []driver.ColumnDef{{Column: driver.Column{Name: "ID", Type: "NUMBER"}}}, PrimaryKey: []string{"ID"}})
	if err != nil || !strings.Contains(stmts[0], "\n  PRIMARY KEY (\"ID\")\n") || !strings.HasPrefix(stmts[0], `CREATE TABLE "HR"."TTTT`) {
		t.Errorf("long name: %v %q", err, stmts)
	}
}

func TestCreateTableErrors(t *testing.T) {
	cols := func(cs ...driver.Column) []driver.ColumnDef {
		out := make([]driver.ColumnDef, len(cs))
		for i, c := range cs {
			out[i].Column = c
		}
		return out
	}
	a := driver.Column{Name: "A", Type: "NUMBER"}
	table := func(def driver.TableDef) driver.TableDef {
		def.Ref.Name = "T"
		if def.Columns == nil {
			def.Columns = cols(a)
		}
		return def
	}
	fk := driver.ForeignKey{Name: "FK", Columns: []string{"A"}, RefTable: driver.ObjectRef{Name: "P"}, RefColumns: []string{"ID"}}
	onUpdate, setDefault := fk, fk
	onUpdate.OnUpdate, setDefault.OnDelete = "CASCADE", "SET DEFAULT"
	cases := map[string]driver.TableDef{
		"give the table a name":                                      {Columns: cols(a)},
		"a table needs at least one column":                          {Ref: driver.ObjectRef{Name: "T"}},
		"column A needs a type":                                      table(driver.TableDef{Columns: cols(driver.Column{Name: "A"})}),
		"always virtual":                                             table(driver.TableDef{Columns: cols(driver.Column{Name: "A", Generated: "1", GeneratedStored: true})}),
		"column A is listed twice":                                   table(driver.TableDef{Columns: cols(a, a)}),
		"foreign key FK: Oracle foreign keys have no ON UPDATE rule": table(driver.TableDef{ForeignKeys: []driver.ForeignKey{onUpdate}}),
		"CASCADE or SET NULL only, not SET DEFAULT":                  table(driver.TableDef{ForeignKeys: []driver.ForeignKey{setDefault}}),
		"index IX: Oracle has no partial indexes":                    table(driver.TableDef{Indexes: []driver.Index{{Name: "IX", Columns: []string{"A"}, Where: "A > 0"}}}),
		"a bitmap index cannot be unique":                            table(driver.TableDef{Indexes: []driver.Index{{Name: "IX", Columns: []string{"A"}, Unique: true, Type: "bitmap"}}}),
		"every index needs a name":                                   table(driver.TableDef{Indexes: []driver.Index{{Columns: []string{"A"}}}}),
		"index IX is a domain index":                                 table(driver.TableDef{Indexes: []driver.Index{{Name: "IX", Columns: []string{"A"}, Type: "domain"}}}),
	}
	for want, def := range cases {
		if _, err := testConn().CreateTableSQL(def); err == nil || !strings.Contains(err.Error(), want) {
			t.Errorf("want error %q, got %v", want, err)
		}
	}
}

func TestAlterUnchanged(t *testing.T) {
	for _, tbl := range []*driver.Table{describedCustomers(), describedOrders(), ddlTableOnly()} {
		if stmts := alterSQL(t, tbl, tableDef(tbl)); len(stmts) != 0 {
			t.Errorf("%s: unchanged definition produced:\n%s", tbl.Ref.Name, strings.Join(stmts, "\n"))
		}
	}
	// The editor may leave out what Describe reports only for display.
	tbl := describedCustomers()
	def := tableDef(tbl)
	for i := range def.Indexes {
		def.Indexes[i].Definition = ""
		if def.Indexes[i].Type == "btree" {
			def.Indexes[i].Type, def.Indexes[i].Desc = "", nil
		}
	}
	def.Indexes = def.Indexes[1:] // primary entries are ignored
	def.Ref.Kind, def.Options = "", nil
	def.Columns[0].Default = nil // identity without its clause
	def.Columns[2].Type = "varchar2(200  byte)"
	for i := range def.ForeignKeys {
		def.ForeignKeys[i].RefTable.Schema = ""
	}
	if stmts := alterSQL(t, tbl, def); len(stmts) != 0 {
		t.Errorf("equivalent definition produced:\n%s", strings.Join(stmts, "\n"))
	}
	orders := describedOrders()
	def = tableDef(orders)
	def.ForeignKeys[0].RefTable.Schema, def.ForeignKeys[0].OnDelete, def.ForeignKeys[0].Table = "", "cascade", nil
	if stmts := alterSQL(t, orders, def); len(stmts) != 0 {
		t.Errorf("equivalent foreign key produced:\n%s", strings.Join(stmts, "\n"))
	}
}

// ddlTableOnly is the fixture of TestTableDDL, which carries identity in the
// default only.
func ddlTableOnly() *driver.Table {
	tbl, _ := ddlTable()
	return tbl
}

func TestAlterColumns(t *testing.T) {
	tbl := describedCustomers()
	def := tableDef(tbl)
	def.Columns[1].Name = "FULL_NAME"                                          // NAME renamed
	def.Columns[2].Type, def.Columns[2].Nullable = "VARCHAR2(320 BYTE)", false // EMAIL widened, required
	def.Columns[2].Comment = ""
	def.Columns[3].Default = nil                                             // CREATED loses its default
	def.Columns[4].Default, def.Columns[4].Comment = strp("100"), "In cents" // BALANCE
	def.Columns[6].Generated = `LOWER("FULL_NAME")`                          // NAME_UPPER
	def.Columns = append(def.Columns[:5], def.Columns[6:]...)                // STATUS dropped
	def.Columns = append(def.Columns, driver.ColumnDef{Column: driver.Column{Name: "TAGS", Type: "VARCHAR2(200 CHAR)", Nullable: true, Default: strp("'none'"), Comment: "Labels"}})
	def.Comment = ""
	def.Ref.Name = "RS_CLIENTS"
	wantStatements(t, alterSQL(t, tbl, def), []string{
		`DROP INDEX "SHOP"."RS_CUSTOMERS_LOWER_IX"`, // on LOWER("EMAIL"), which changes type
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" DROP COLUMN "STATUS"`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" RENAME COLUMN "NAME" TO "FULL_NAME"`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("EMAIL" VARCHAR2(320 BYTE) NOT NULL)`,
		`COMMENT ON COLUMN "SHOP"."RS_CUSTOMERS"."EMAIL" IS ''`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("CREATED" DEFAULT NULL)`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("BALANCE" DEFAULT 100)`,
		`COMMENT ON COLUMN "SHOP"."RS_CUSTOMERS"."BALANCE" IS 'In cents'`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("NAME_UPPER" AS (LOWER("FULL_NAME")))`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" ADD ("TAGS" VARCHAR2(200 CHAR) DEFAULT 'none')`,
		`COMMENT ON COLUMN "SHOP"."RS_CUSTOMERS"."TAGS" IS 'Labels'`,
		`CREATE INDEX "SHOP"."RS_CUSTOMERS_LOWER_IX" ON "SHOP"."RS_CUSTOMERS" (LOWER("EMAIL"))`,
		`COMMENT ON TABLE "SHOP"."RS_CUSTOMERS" IS ''`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" RENAME TO "RS_CLIENTS"`,
	})

	// Nullability is only sent when it changes; NULL on its own too.
	def = tableDef(tbl)
	def.Columns[1].Nullable = true
	def.Columns[6].Type, def.Columns[6].Nullable = "VARCHAR2(500 CHAR)", false
	wantStatements(t, alterSQL(t, tbl, def), []string{
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("NAME" NULL)`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("NAME_UPPER" VARCHAR2(500 CHAR) AS (UPPER("NAME")))`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("NAME_UPPER" NOT NULL)`,
	})
}

func TestAlterDefaultOnNull(t *testing.T) {
	tbl := describedCustomers() // STATUS: DEFAULT ON NULL 'new', NOT NULL
	cases := []struct {
		def      *string
		nullable bool
		want     []string
	}{
		{strp("ON NULL 'open'"), false, []string{`MODIFY ("STATUS" DEFAULT ON NULL 'open')`}},
		// Leaving ON NULL drops its NOT NULL, which has to be restored.
		{strp("'open'"), false, []string{`MODIFY ("STATUS" DEFAULT 'open')`, `MODIFY ("STATUS" NOT NULL)`}},
		{nil, true, []string{`MODIFY ("STATUS" DEFAULT NULL)`}},
	}
	for _, tc := range cases {
		def := tableDef(tbl)
		def.Columns[5].Default, def.Columns[5].Nullable = tc.def, tc.nullable
		var want []string
		for _, w := range tc.want {
			want = append(want, `ALTER TABLE "SHOP"."RS_CUSTOMERS" `+w)
		}
		wantStatements(t, alterSQL(t, tbl, def), want)
	}
	def := tableDef(tbl)
	def.Columns[5].Nullable = true
	if _, err := testConn().AlterTableSQL(tbl, def); err == nil || !strings.Contains(err.Error(), "DEFAULT ON NULL") {
		t.Errorf("nullable ON NULL column: %v", err)
	}
	// Adopting ON NULL makes a nullable column NOT NULL by itself.
	def = tableDef(tbl)
	def.Columns[4].Default, def.Columns[4].Nullable = strp("ON NULL 0"), false
	wantStatements(t, alterSQL(t, tbl, def), []string{`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("BALANCE" DEFAULT ON NULL 0)`})
}

func TestAlterIdentity(t *testing.T) {
	tbl := describedCustomers()
	def := tableDef(tbl)
	def.Columns[0].Default = strp("GENERATED ALWAYS AS IDENTITY")
	wantStatements(t, alterSQL(t, tbl, def), []string{`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("ID" GENERATED ALWAYS AS IDENTITY)`})

	// Switching auto-increment off drops the identity, whatever the stale
	// clause in the default says; a new plain default follows.
	def = tableDef(tbl)
	def.Columns[0].AutoIncrement = false
	wantStatements(t, alterSQL(t, tbl, def), []string{`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("ID" DROP IDENTITY)`})
	def.Columns[0].Default = strp("0")
	wantStatements(t, alterSQL(t, tbl, def), []string{
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("ID" DROP IDENTITY)`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("ID" DEFAULT 0)`,
	})

	for _, set := range []func(*driver.ColumnDef){
		func(c *driver.ColumnDef) { c.AutoIncrement = true },
		func(c *driver.ColumnDef) { c.Default = strp("GENERATED ALWAYS AS IDENTITY") },
	} {
		def = tableDef(tbl)
		set(defColumn(&def, "BALANCE"))
		if _, err := testConn().AlterTableSQL(tbl, def); err == nil || err.Error() != "Oracle cannot make existing column BALANCE an identity column; add a new column instead" {
			t.Errorf("identity on existing column: %v", err)
		}
	}
	// New columns can be identities.
	o := describedOrders()
	def = tableDef(o)
	def.Columns = append(def.Columns, driver.ColumnDef{Column: driver.Column{Name: "SEQ", Type: "NUMBER", AutoIncrement: true, Nullable: true}})
	wantStatements(t, alterSQL(t, o, def), []string{`ALTER TABLE "SHOP"."RS_ORDERS" ADD ("SEQ" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY)`})
}

func TestAlterColumnErrors(t *testing.T) {
	tbl := describedCustomers()
	cases := []struct {
		want string
		set  func(*driver.TableDef)
	}{
		{"Oracle cannot turn column NAME_UPPER into or out of a generated column", func(d *driver.TableDef) { defColumn(d, "NAME_UPPER").Generated = "" }},
		{"Oracle cannot turn column EMAIL into or out of a generated column", func(d *driver.TableDef) { defColumn(d, "EMAIL").Generated = `LOWER("NAME")` }},
		{"always virtual", func(d *driver.TableDef) { defColumn(d, "NAME_UPPER").GeneratedStored = true }},
		{"column GONE no longer exists; reload the structure", func(d *driver.TableDef) { d.Columns[1].OriginalName = "GONE" }},
		{"column ID is part of the primary key, which keeps it NOT NULL", func(d *driver.TableDef) { defColumn(d, "ID").Nullable = true }},
		{"no ON UPDATE clause for columns", func(d *driver.TableDef) { defColumn(d, "CREATED").OnUpdate = "SYSDATE" }},
		{"column EMAIL is listed twice", func(d *driver.TableDef) { defColumn(d, "NAME").Name = "EMAIL" }},
		{"every column needs a name", func(d *driver.TableDef) { defColumn(d, "NAME").Name = "" }},
	}
	for _, tc := range cases {
		def := tableDef(tbl)
		tc.set(&def)
		if _, err := testConn().AlterTableSQL(tbl, def); err == nil || !strings.Contains(err.Error(), tc.want) {
			t.Errorf("want %q, got %v", tc.want, err)
		}
	}
}

func TestAlterConstraints(t *testing.T) {
	tbl := describedCustomers()
	def := tableDef(tbl)
	def.Checks = []driver.Check{{Name: "RS_CUSTOMERS_BALANCE_CK", Expression: "BALANCE >= -100"}, {Name: "RS_CUSTOMERS_NAME_CK", Expression: "NAME IS NOT NULL"}}
	def.Indexes = []driver.Index{
		{Name: "RS_CUSTOMERS_EMAIL_UK", Columns: []string{"EMAIL", "NAME"}, Unique: true},        // unique constraint widened
		{Name: "RS_CUSTOMERS_LOWER_IX", Columns: []string{`LOWER("EMAIL")`}, Desc: []bool{true}}, // now descending
		{Name: "RS_CUSTOMERS_BAL_BX", Columns: []string{"BALANCE"}, Type: "bitmap"},
	}
	wantStatements(t, alterSQL(t, tbl, def), []string{
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" DROP CONSTRAINT "RS_CUSTOMERS_BALANCE_CK"`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" DROP CONSTRAINT "SYS_C008431"`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" DROP CONSTRAINT "RS_CUSTOMERS_EMAIL_UK" DROP INDEX`,
		`DROP INDEX "SHOP"."RS_CUSTOMERS_LOWER_IX"`,
		`DROP INDEX "SHOP"."RS_CUSTOMERS_REV_IX"`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" ADD CONSTRAINT "RS_CUSTOMERS_EMAIL_UK" UNIQUE ("EMAIL", "NAME")`,
		`CREATE INDEX "SHOP"."RS_CUSTOMERS_LOWER_IX" ON "SHOP"."RS_CUSTOMERS" (LOWER("EMAIL") DESC)`,
		`CREATE BITMAP INDEX "SHOP"."RS_CUSTOMERS_BAL_BX" ON "SHOP"."RS_CUSTOMERS" ("BALANCE")`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" ADD CONSTRAINT "RS_CUSTOMERS_BALANCE_CK" CHECK (BALANCE >= -100)`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" ADD CONSTRAINT "RS_CUSTOMERS_NAME_CK" CHECK (NAME IS NOT NULL)`,
	})

	// Keys other tables reference cannot go.
	def = tableDef(tbl)
	def.PrimaryKey = []string{"ID", "EMAIL"}
	if _, err := testConn().AlterTableSQL(tbl, def); err == nil ||
		err.Error() != "the primary key is referenced by foreign key RS_ORDERS.RS_ORDERS_CUSTOMER_FK; drop that foreign key first" {
		t.Errorf("referenced primary key: %v", err)
	}

	// Primary key and foreign keys of a table nobody references.
	o := describedOrders()
	def = tableDef(o)
	def.PrimaryKey = []string{"ID", "REGION"}
	def.ForeignKeys[0].OnDelete = "SET NULL"
	def.ForeignKeys = append(def.ForeignKeys, driver.ForeignKey{Name: "RS_ORDERS_SELF_FK", Columns: []string{"TOTAL"}, RefTable: driver.ObjectRef{Schema: "SALES", Name: "TOTALS"}, RefColumns: []string{"AMOUNT"}})
	def.Indexes = def.Indexes[:1]
	wantStatements(t, alterSQL(t, o, def), []string{
		`ALTER TABLE "SHOP"."RS_ORDERS" DROP CONSTRAINT "RS_ORDERS_CUSTOMER_FK"`,
		`ALTER TABLE "SHOP"."RS_ORDERS" DROP PRIMARY KEY DROP INDEX`,
		`DROP INDEX "SHOP"."RS_ORDERS_REGION_BX"`,
		`ALTER TABLE "SHOP"."RS_ORDERS" ADD CONSTRAINT "RS_ORDERS_PK" PRIMARY KEY ("ID", "REGION")`,
		`ALTER TABLE "SHOP"."RS_ORDERS" ADD CONSTRAINT "RS_ORDERS_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "SHOP"."RS_CUSTOMERS" ("ID") ON DELETE SET NULL`,
		`ALTER TABLE "SHOP"."RS_ORDERS" ADD CONSTRAINT "RS_ORDERS_SELF_FK" FOREIGN KEY ("TOTAL") REFERENCES "SALES"."TOTALS" ("AMOUNT")`,
	})

	// A system-named primary key is replaced by TABLE_PK; removing it is enough.
	def = tableDef(tbl)
	def.PrimaryKey = nil
	tbl.Referenced = nil
	wantStatements(t, alterSQL(t, tbl, def), []string{`ALTER TABLE "SHOP"."RS_CUSTOMERS" DROP PRIMARY KEY DROP INDEX`})
	def.PrimaryKey = []string{"EMAIL"}
	def.Ref.Name = "RS_PEOPLE"
	wantStatements(t, alterSQL(t, tbl, def), []string{
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" DROP PRIMARY KEY DROP INDEX`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" ADD CONSTRAINT "RS_PEOPLE_PK" PRIMARY KEY ("EMAIL")`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" RENAME TO "RS_PEOPLE"`,
	})

	for want, set := range map[string]func(*driver.TableDef){
		"Oracle foreign keys have no ON UPDATE rule": func(d *driver.TableDef) { d.ForeignKeys[0].OnUpdate = "CASCADE" },
		"not SET DEFAULT":    func(d *driver.TableDef) { d.ForeignKeys[0].OnDelete = "SET DEFAULT" },
		"no partial indexes": func(d *driver.TableDef) { d.Indexes[1].Where = "REGION IS NOT NULL" },
		"cannot be unique":   func(d *driver.TableDef) { d.Indexes[1].Unique = true },
	} {
		def := tableDef(o)
		set(&def)
		if _, err := testConn().AlterTableSQL(o, def); err == nil || !strings.Contains(err.Error(), want) {
			t.Errorf("want %q, got %v", want, err)
		}
	}
}

// Renaming a column carries its keys and indexes along in Oracle, whether
// the editor renames them in the definition or keeps the old name.
func TestAlterRenameKeepsKeys(t *testing.T) {
	o := describedOrders()
	o.Indexes = append(o.Indexes, driver.Index{Name: "RS_ORDERS_CUST_IX", Columns: []string{"CUSTOMER_ID", "ID"}, Type: "btree", Desc: []bool{false, true}})
	for _, follow := range []bool{false, true} {
		def := tableDef(o)
		def.Columns[0].Name, def.Columns[1].Name = "ORDER_ID", "CLIENT_ID"
		if follow {
			def.PrimaryKey = []string{"ORDER_ID"}
			def.ForeignKeys[0].Columns = []string{"CLIENT_ID"}
			def.Indexes[2].Columns = []string{"CLIENT_ID", "ORDER_ID"}
		}
		wantStatements(t, alterSQL(t, o, def), []string{
			`ALTER TABLE "SHOP"."RS_ORDERS" RENAME COLUMN "ID" TO "ORDER_ID"`,
			`ALTER TABLE "SHOP"."RS_ORDERS" RENAME COLUMN "CUSTOMER_ID" TO "CLIENT_ID"`,
		})
	}
	// Swapping two names is still a change of the index.
	def := tableDef(o)
	def.Indexes[2].Columns = []string{"ID", "CUSTOMER_ID"}
	stmts := alterSQL(t, o, def)
	if len(stmts) != 2 || !strings.HasPrefix(stmts[1], `CREATE INDEX "SHOP"."RS_ORDERS_CUST_IX" ON "SHOP"."RS_ORDERS" ("ID", "CUSTOMER_ID" DESC)`) {
		t.Errorf("changed index:\n%s", strings.Join(stmts, "\n"))
	}
}

func TestAlterNotATable(t *testing.T) {
	if _, err := testConn().AlterTableSQL(&driver.Table{Ref: driver.ObjectRef{Name: "V"}, Kind: "materialized_view"}, driver.TableDef{}); err == nil ||
		err.Error() != "V is a materialized view, not a table" {
		t.Errorf("view: %v", err)
	}
	if _, err := testConn().AlterTableSQL(nil, driver.TableDef{}); err == nil {
		t.Error("nil table accepted")
	}
}

func TestDropTruncateRename(t *testing.T) {
	c := testConn()
	ref := func(kind, name string) driver.ObjectRef {
		return driver.ObjectRef{Schema: "SHOP", Name: name, Kind: kind}
	}
	drops := []struct {
		ref     driver.ObjectRef
		cascade bool
		want    string
	}{
		{ref("table", "T"), false, `DROP TABLE "SHOP"."T"`},
		{ref("table", "T"), true, `DROP TABLE "SHOP"."T" CASCADE CONSTRAINTS`},
		{ref("view", "V"), true, `DROP VIEW "SHOP"."V" CASCADE CONSTRAINTS`},
		{ref("materialized_view", "MV"), true, `DROP MATERIALIZED VIEW "SHOP"."MV"`},
		{ref("sequence", "S"), false, `DROP SEQUENCE "SHOP"."S"`},
		{ref("synonym", "S"), false, `DROP SYNONYM "SHOP"."S"`},
		{ref("package", "P"), false, `DROP PACKAGE "SHOP"."P"`},
		{ref("package_body", "P"), false, `DROP PACKAGE BODY "SHOP"."P"`},
		{ref("procedure", "P"), false, `DROP PROCEDURE "SHOP"."P"`},
		{ref("function", "F"), false, `DROP FUNCTION "SHOP"."F"`},
		{ref("trigger", "TR"), false, `DROP TRIGGER "SHOP"."TR"`},
		{ref("type", "TY"), true, `DROP TYPE "SHOP"."TY" FORCE`},
		{ref("index", "IX"), false, `DROP INDEX "SHOP"."IX"`},
		{driver.ObjectRef{Name: "T", Kind: "table"}, false, `DROP TABLE "SHOP"."T"`},
	}
	for _, d := range drops {
		got, err := c.DropObjectSQL(d.ref, d.cascade)
		if err != nil || len(got) != 1 || got[0] != d.want {
			t.Errorf("drop %+v: %q %v", d.ref, got, err)
		}
	}
	if _, err := c.DropObjectSQL(ref("database", "X"), false); err == nil {
		t.Error("unknown kind accepted")
	}
	if got, err := c.TruncateSQL(ref("table", "T")); err != nil || got[0] != `TRUNCATE TABLE "SHOP"."T"` {
		t.Errorf("truncate %q %v", got, err)
	}
	if _, err := c.TruncateSQL(ref("view", "V")); err == nil {
		t.Error("truncating a view accepted")
	}

	renames := map[driver.ObjectRef]string{
		ref("table", "T"):             `ALTER TABLE "SHOP"."T" RENAME TO "N"`,
		{Schema: "HR", Name: "T"}:     `ALTER TABLE "HR"."T" RENAME TO "N"`,
		ref("index", "IX"):            `ALTER INDEX "SHOP"."IX" RENAME TO "N"`,
		ref("trigger", "TR"):          `ALTER TRIGGER "SHOP"."TR" RENAME TO "N"`,
		ref("view", "V"):              `RENAME "V" TO "N"`,
		{Name: "S", Kind: "sequence"}: `RENAME "S" TO "N"`,
		ref("synonym", "SY"):          `RENAME "SY" TO "N"`,
	}
	for r, want := range renames {
		if got, err := c.RenameObjectSQL(r, "N"); err != nil || len(got) != 1 || got[0] != want {
			t.Errorf("rename %+v: %q %v", r, got, err)
		}
	}
	for r, want := range map[driver.ObjectRef]string{
		{Schema: "HR", Name: "V", Kind: "view"}: "Oracle can only rename a view in your own schema (SHOP)",
		ref("procedure", "P"):                   "Oracle cannot rename a procedure; recreate it under the new name",
		ref("materialized_view", "MV"):          "Oracle cannot rename a materialized view; recreate it under the new name",
	} {
		if _, err := c.RenameObjectSQL(r, "N"); err == nil || err.Error() != want {
			t.Errorf("rename %+v: %v", r, err)
		}
	}
	if _, err := c.RenameObjectSQL(ref("table", "T"), " "); err == nil {
		t.Error("empty name accepted")
	}
	if _, err := c.CreateDatabaseSQL("X", nil); err == nil || !strings.Contains(err.Error(), "pluggable databases") {
		t.Errorf("create database: %v", err)
	}
	if _, err := c.DropDatabaseSQL("X"); err == nil {
		t.Error("drop database accepted")
	}
}

func TestDesign(t *testing.T) {
	info := oracleDriver{}.Info()
	d := info.Design
	if !info.Caps.DDL || d == nil {
		t.Fatalf("caps %+v design %v", info.Caps, d)
	}
	if !d.Columns || !d.AutoIncrement || !d.ColumnComments || !d.TableComment || !d.Generated || !d.GeneratedVirtual || !d.Checks ||
		!d.PrimaryKey || !d.ForeignKeys || !d.Indexes || d.ReorderColumns || d.PartialIndexes || d.OnUpdate || d.Collation || d.IndexLengths {
		t.Errorf("design %+v", d)
	}
	if d.IndexTypes[0] != "btree" || d.FKActions[0] != "NO ACTION" || d.Note == "" {
		t.Errorf("design %+v", d)
	}
	// Every offered index type and rule is accepted.
	for _, typ := range d.IndexTypes {
		if _, err := testConn().createIndex(`"T"`, "SHOP", driver.Index{Name: "IX", Type: typ}, []string{"A"}, nil); err != nil {
			t.Errorf("index type %s: %v", typ, err)
		}
	}
	for _, rule := range d.FKActions {
		if _, err := deleteRule(driver.ForeignKey{OnDelete: rule, OnUpdate: "NO ACTION"}); err != nil {
			t.Errorf("rule %s: %v", rule, err)
		}
	}
}

// Oracle refuses some column changes under indexes and virtual columns;
// the indexes are rebuilt around the change, the rest is refused up front.
func TestAlterDependencies(t *testing.T) {
	tbl := describedCustomers()
	tbl.Indexes = append(tbl.Indexes, driver.Index{Name: "RS_CUSTOMERS_NU_IX", Columns: []string{"NAME_UPPER"}, Type: "btree", Desc: []bool{false}})

	// Retyping EMAIL rebuilds the function-based index on LOWER("EMAIL"),
	// under the column's new name.
	def := tableDef(tbl)
	email := defColumn(&def, "EMAIL")
	email.Name, email.Type = "MAIL", "VARCHAR2(320 BYTE)"
	wantStatements(t, alterSQL(t, tbl, def), []string{
		`DROP INDEX "SHOP"."RS_CUSTOMERS_LOWER_IX"`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" RENAME COLUMN "EMAIL" TO "MAIL"`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("MAIL" VARCHAR2(320 BYTE))`,
		`CREATE INDEX "SHOP"."RS_CUSTOMERS_LOWER_IX" ON "SHOP"."RS_CUSTOMERS" (LOWER("MAIL"))`,
	})

	// A new virtual expression rebuilds the indexes on that column.
	def = tableDef(tbl)
	defColumn(&def, "NAME_UPPER").Generated = `LOWER("NAME")`
	wantStatements(t, alterSQL(t, tbl, def), []string{
		`DROP INDEX "SHOP"."RS_CUSTOMERS_NU_IX"`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("NAME_UPPER" AS (LOWER("NAME")))`,
		`CREATE INDEX "SHOP"."RS_CUSTOMERS_NU_IX" ON "SHOP"."RS_CUSTOMERS" ("NAME_UPPER")`,
	})

	// Renaming NAME alone changes nothing else: Oracle updates the virtual
	// column and the check that use it. Changed ones are written with the
	// new name even when the definition still has the old one.
	tbl.Checks = append(tbl.Checks, driver.Check{Name: "RS_CUSTOMERS_NAME_CK", Expression: `"NAME" <> '"NAME"'`})
	def = tableDef(tbl)
	defColumn(&def, "NAME").Name = "FULL_NAME"
	wantStatements(t, alterSQL(t, tbl, def), []string{`ALTER TABLE "SHOP"."RS_CUSTOMERS" RENAME COLUMN "NAME" TO "FULL_NAME"`})
	defColumn(&def, "NAME_UPPER").Type = "VARCHAR2(500 CHAR)"
	def.Checks[2].Expression = `"NAME" NOT IN ('"NAME"', 'x')`
	wantStatements(t, alterSQL(t, tbl, def), []string{
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" DROP CONSTRAINT "RS_CUSTOMERS_NAME_CK"`,
		`DROP INDEX "SHOP"."RS_CUSTOMERS_NU_IX"`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" RENAME COLUMN "NAME" TO "FULL_NAME"`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("NAME_UPPER" VARCHAR2(500 CHAR) AS (UPPER("FULL_NAME")))`,
		`CREATE INDEX "SHOP"."RS_CUSTOMERS_NU_IX" ON "SHOP"."RS_CUSTOMERS" ("NAME_UPPER")`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" ADD CONSTRAINT "RS_CUSTOMERS_NAME_CK" CHECK ("FULL_NAME" NOT IN ('"NAME"', 'x'))`,
	})

	// NAME cannot be retyped while NAME_UPPER uses it, unless it goes.
	def = tableDef(tbl)
	defColumn(&def, "NAME").Type = "VARCHAR2(200 CHAR)"
	if _, err := testConn().AlterTableSQL(tbl, def); err == nil ||
		err.Error() != "column NAME is used by virtual column NAME_UPPER, so Oracle cannot change its type; drop NAME_UPPER first" {
		t.Errorf("retyping a column a virtual column uses: %v", err)
	}
	var cols []driver.ColumnDef
	for _, col := range def.Columns {
		if col.Name != "NAME_UPPER" {
			cols = append(cols, col)
		}
	}
	def.Columns = cols
	def.Indexes = def.Indexes[:len(def.Indexes)-1]
	wantStatements(t, alterSQL(t, tbl, def), []string{
		`DROP INDEX "SHOP"."RS_CUSTOMERS_NU_IX"`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" DROP COLUMN "NAME_UPPER"`,
		`ALTER TABLE "SHOP"."RS_CUSTOMERS" MODIFY ("NAME" VARCHAR2(200 CHAR))`,
	})
}

func TestAlterSelfReference(t *testing.T) {
	self := driver.ObjectRef{Schema: "SHOP", Name: "EMP", Kind: "table"}
	fk := driver.ForeignKey{Name: "EMP_MANAGER_FK", Columns: []string{"MANAGER_ID"}, RefTable: self, RefColumns: []string{"ID"}, OnDelete: "SET NULL", Table: &self}
	emp := &driver.Table{Ref: self, Kind: "table",
		Columns:     []driver.Column{{Name: "ID", Type: "NUMBER"}, {Name: "MANAGER_ID", Type: "NUMBER", Nullable: true}},
		PrimaryKey:  []string{"ID"},
		Indexes:     []driver.Index{{Name: "EMP_PK", Columns: []string{"ID"}, Unique: true, Primary: true}},
		ForeignKeys: []driver.ForeignKey{fk}, Referenced: []driver.ForeignKey{fk},
	}
	for _, follow := range []bool{false, true} {
		def := tableDef(emp)
		def.Columns[0].Name, def.Ref.Name = "EMP_ID", "STAFF"
		if follow {
			def.PrimaryKey, def.ForeignKeys[0].RefColumns, def.ForeignKeys[0].RefTable.Name = []string{"EMP_ID"}, []string{"EMP_ID"}, "STAFF"
		}
		wantStatements(t, alterSQL(t, emp, def), []string{
			`ALTER TABLE "SHOP"."EMP" RENAME COLUMN "ID" TO "EMP_ID"`,
			`ALTER TABLE "SHOP"."EMP" RENAME TO "STAFF"`,
		})
	}
	// Its own foreign key does not stop the key from changing when it goes too.
	def := tableDef(emp)
	def.PrimaryKey, def.ForeignKeys = []string{"ID", "MANAGER_ID"}, nil
	wantStatements(t, alterSQL(t, emp, def), []string{
		`ALTER TABLE "SHOP"."EMP" DROP CONSTRAINT "EMP_MANAGER_FK"`,
		`ALTER TABLE "SHOP"."EMP" DROP PRIMARY KEY DROP INDEX`,
		`ALTER TABLE "SHOP"."EMP" ADD CONSTRAINT "EMP_PK" PRIMARY KEY ("ID", "MANAGER_ID")`,
	})
	def.ForeignKeys = tableDef(emp).ForeignKeys
	if _, err := testConn().AlterTableSQL(emp, def); err == nil ||
		err.Error() != "the primary key is referenced by foreign key EMP.EMP_MANAGER_FK; drop that foreign key first" {
		t.Errorf("kept self reference: %v", err)
	}

	// A referenced column cannot be dropped either.
	tbl := describedCustomers()
	tbl.Referenced = append(tbl.Referenced, driver.ForeignKey{Name: "RS_LOGINS_EMAIL_FK", RefColumns: []string{"EMAIL"}, Table: &driver.ObjectRef{Schema: "SHOP", Name: "RS_LOGINS"}})
	def = tableDef(tbl)
	def.Columns = append(def.Columns[:2], def.Columns[3:]...)
	if _, err := testConn().AlterTableSQL(tbl, def); err == nil ||
		err.Error() != "column EMAIL is referenced by foreign key RS_LOGINS.RS_LOGINS_EMAIL_FK; drop that foreign key first" {
		t.Errorf("referenced column: %v", err)
	}
	def.Indexes = def.Indexes[:1]
	if _, err := testConn().AlterTableSQL(tbl, def); err == nil || !strings.HasPrefix(err.Error(), "unique key RS_CUSTOMERS_EMAIL_UK is referenced") {
		t.Errorf("referenced unique key: %v", err)
	}
}
