package oracle

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"os"
	"strings"
	"sync"
	"testing"
	"time"

	"rowsmith/internal/driver"
	"rowsmith/internal/driver/sqlbase"
)

// The integration test needs a server, e.g. the dev container:
//
//	ROWSMITH_TEST_ORACLE_HOST=oracle ROWSMITH_TEST_ORACLE_PASSWORD=... go test -run Integration ./internal/driver/oracle/
//
// Optional: ROWSMITH_TEST_ORACLE_PORT, ROWSMITH_TEST_ORACLE_SERVICE (FREEPDB1),
// ROWSMITH_TEST_ORACLE_USER (shop) and ROWSMITH_TEST_ORACLE_SYSTEM_PASSWORD
// (defaults to the password; SYSTEM checks are skipped when it fails).

func testParams(t *testing.T, user, password string) driver.OpenParams {
	host := os.Getenv("ROWSMITH_TEST_ORACLE_HOST")
	if host == "" {
		t.Skip("set ROWSMITH_TEST_ORACLE_HOST to run Oracle integration tests")
	}
	service := os.Getenv("ROWSMITH_TEST_ORACLE_SERVICE")
	if service == "" {
		service = "FREEPDB1"
	}
	params := map[string]any{"host": host, "service": service, "user": user, "connectTimeout": 20}
	if port := os.Getenv("ROWSMITH_TEST_ORACLE_PORT"); port != "" {
		params["port"] = port
	}
	return driver.OpenParams{Params: params, Secrets: map[string]string{"password": password}, AppName: "rowsmith-test"}
}

func appUser() string {
	if u := os.Getenv("ROWSMITH_TEST_ORACLE_USER"); u != "" {
		return u
	}
	return "shop"
}

func systemPassword() string {
	if p := os.Getenv("ROWSMITH_TEST_ORACLE_SYSTEM_PASSWORD"); p != "" {
		return p
	}
	return os.Getenv("ROWSMITH_TEST_ORACLE_PASSWORD")
}

func mustOpen(t *testing.T, p driver.OpenParams) *conn {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()
	c, err := oracleDriver{}.Open(ctx, p)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	t.Cleanup(func() { c.Close() })
	return c.(*conn)
}

var fixtureDrops = []string{
	"DROP TABLE RS_ORDERS PURGE", "DROP TABLE RS_CUSTOMERS PURGE", "DROP TABLE RS_LOG PURGE", "DROP TABLE RS_SHAPES PURGE",
	"DROP TABLE RS_TMP PURGE", "DROP VIEW RS_CUSTOMER_ORDERS", "DROP SEQUENCE RS_SEQ", "DROP PROCEDURE RS_GREET",
	"DROP PROCEDURE RS_BAD", "DROP PACKAGE RS_PKG", "DROP TYPE RS_POINT_T FORCE", "DROP SYNONYM RS_CUST",
	"DROP MATERIALIZED VIEW RS_TOTALS", "DROP TABLE RS_MODERN PURGE",
}

var fixture = []string{
	`CREATE TABLE RS_CUSTOMERS (
		ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		NAME VARCHAR2(100 CHAR) NOT NULL,
		EMAIL VARCHAR2(200) CONSTRAINT RS_CUSTOMERS_EMAIL_UK UNIQUE,
		CREATED DATE DEFAULT SYSDATE,
		BALANCE NUMBER(12,2) DEFAULT 0,
		NAME_UPPER GENERATED ALWAYS AS (UPPER(NAME)) VIRTUAL,
		NOTES CLOB,
		AVATAR BLOB,
		UPDATED_AT TIMESTAMP(6),
		SEEN_AT TIMESTAMP WITH TIME ZONE,
		SCORE BINARY_DOUBLE,
		CONSTRAINT RS_CUSTOMERS_BALANCE_CK CHECK (BALANCE >= 0))`,
	`COMMENT ON TABLE RS_CUSTOMERS IS 'Customers'`,
	`COMMENT ON COLUMN RS_CUSTOMERS.EMAIL IS 'Login email'`,
	`CREATE INDEX RS_CUSTOMERS_LOWER_IX ON RS_CUSTOMERS (LOWER(EMAIL))`,
	`CREATE TABLE RS_ORDERS (
		ID NUMBER(10) PRIMARY KEY,
		CUSTOMER_ID NUMBER(10) NOT NULL,
		TOTAL NUMBER(12,2),
		PLACED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
		STATUS VARCHAR2(20),
		CONSTRAINT RS_ORDERS_CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES RS_CUSTOMERS (ID) ON DELETE CASCADE)`,
	`CREATE INDEX RS_ORDERS_CUSTOMER_IX ON RS_ORDERS (CUSTOMER_ID, PLACED_AT DESC)`,
	`CREATE TABLE RS_LOG (MSG VARCHAR2(200), AT DATE)`,
	`CREATE OR REPLACE TYPE RS_POINT_T AS OBJECT (X NUMBER, Y NUMBER)`,
	`CREATE TABLE RS_SHAPES (ID NUMBER(10) PRIMARY KEY, PT RS_POINT_T)`,
	`INSERT INTO RS_SHAPES VALUES (1, RS_POINT_T(1, 2))`,
	`CREATE OR REPLACE VIEW RS_CUSTOMER_ORDERS AS SELECT c.NAME, COUNT(o.ID) AS ORDERS
		FROM RS_CUSTOMERS c LEFT JOIN RS_ORDERS o ON o.CUSTOMER_ID = c.ID GROUP BY c.NAME`,
	`CREATE SEQUENCE RS_SEQ START WITH 100 INCREMENT BY 5`,
	`CREATE OR REPLACE PROCEDURE RS_GREET(p_name VARCHAR2) IS
BEGIN
  DBMS_OUTPUT.PUT_LINE('Hello, ' || p_name);
END;`,
	`CREATE OR REPLACE PACKAGE RS_PKG AS
  FUNCTION twice(n NUMBER) RETURN NUMBER;
END RS_PKG;`,
	`CREATE OR REPLACE PACKAGE BODY RS_PKG AS
  FUNCTION twice(n NUMBER) RETURN NUMBER IS
  BEGIN
    RETURN n * 2;
  END;
END RS_PKG;`,
	`CREATE OR REPLACE TRIGGER RS_ORDERS_BI BEFORE INSERT ON RS_ORDERS FOR EACH ROW
BEGIN
  IF :NEW.STATUS IS NULL THEN
    :NEW.STATUS := 'new';
  END IF;
END;`,
	`CREATE SYNONYM RS_CUST FOR RS_CUSTOMERS`,
	`CREATE MATERIALIZED VIEW RS_TOTALS AS SELECT CUSTOMER_ID, SUM(TOTAL) AS TOTAL FROM RS_ORDERS GROUP BY CUSTOMER_ID`,
}

// modernFixture needs Oracle 23ai (BOOLEAN, native JSON and VECTOR columns).
const modernFixture = `CREATE TABLE RS_MODERN (ID NUMBER(10) PRIMARY KEY, FLAG BOOLEAN, DOC JSON, V VECTOR(3, FLOAT32))`

func setupFixture(t *testing.T, c *conn) {
	t.Helper()
	ctx := context.Background()
	for _, q := range fixtureDrops {
		_, _ = c.db.ExecContext(ctx, q)
	}
	for _, q := range fixture {
		if _, err := c.db.ExecContext(ctx, q); err != nil {
			t.Fatalf("fixture %q: %v", q[:min(len(q), 60)], err)
		}
	}
	t.Cleanup(func() {
		for _, q := range fixtureDrops {
			_, _ = c.db.ExecContext(context.Background(), q)
		}
	})
}

// recSink records console output per statement.
type recSink struct {
	stmts []*recStmt
}

type recStmt struct {
	info    driver.StatementInfo
	cols    [][]driver.ResultColumn
	rows    [][]any
	notices []string
	sums    []driver.ResultSummary
	err     error
}

func (s *recSink) cur() *recStmt { return s.stmts[len(s.stmts)-1] }
func (s *recSink) BeginStatement(i driver.StatementInfo) error {
	s.stmts = append(s.stmts, &recStmt{info: i})
	return nil
}
func (s *recSink) Columns(c []driver.ResultColumn) error {
	s.cur().cols = append(s.cur().cols, c)
	return nil
}
func (s *recSink) Rows(r [][]any) error { s.cur().rows = append(s.cur().rows, r...); return nil }
func (s *recSink) EndResult(r driver.ResultSummary) error {
	s.cur().sums = append(s.cur().sums, r)
	return nil
}
func (s *recSink) Notice(level, text string) error {
	s.cur().notices = append(s.cur().notices, level+": "+text)
	return nil
}
func (s *recSink) EndStatement(err error) error { s.cur().err = err; return nil }

func run(t *testing.T, sess driver.Session, script string, opts driver.ExecOptions) *recSink {
	t.Helper()
	s := &recSink{}
	if err := sess.Execute(context.Background(), script, opts, s); err != nil {
		t.Fatalf("execute: %v", err)
	}
	return s
}

func queryErr(t *testing.T, err error) *driver.QueryError {
	t.Helper()
	var qe *driver.QueryError
	if !errors.As(err, &qe) {
		t.Fatalf("want *driver.QueryError, got %T %v", err, err)
	}
	return qe
}

func objectKinds(objs []driver.Object) map[string]driver.Object {
	m := map[string]driver.Object{}
	for _, o := range objs {
		m[o.Kind+":"+o.Name] = o
	}
	return m
}

func column(t *testing.T, tbl *driver.Table, name string) driver.Column {
	t.Helper()
	for _, c := range tbl.Columns {
		if c.Name == name {
			return c
		}
	}
	t.Fatalf("column %s not found in %s", name, tbl.Ref.Name)
	return driver.Column{}
}

func resultCol(t *testing.T, res *driver.Result, name string) int {
	t.Helper()
	for i, c := range res.Columns {
		if c.Name == name {
			return i
		}
	}
	t.Fatalf("result column %s not found", name)
	return -1
}

func TestIntegration(t *testing.T) {
	pw := os.Getenv("ROWSMITH_TEST_ORACLE_PASSWORD")
	p := testParams(t, appUser(), pw)

	// Every connection must go through the dialer, with the host unresolved.
	var dialMu sync.Mutex
	var dialed []string
	p.Dial = func(ctx context.Context, network, addr string) (net.Conn, error) {
		dialMu.Lock()
		dialed = append(dialed, addr)
		dialMu.Unlock()
		return (&net.Dialer{}).DialContext(ctx, network, addr)
	}
	c := mustOpen(t, p)
	setupFixture(t, c)
	ctx := context.Background()
	user := strings.ToUpper(appUser())

	t.Run("Dial", func(t *testing.T) {
		dialMu.Lock()
		defer dialMu.Unlock()
		want := net.JoinHostPort(os.Getenv("ROWSMITH_TEST_ORACLE_HOST"), "1521")
		if os.Getenv("ROWSMITH_TEST_ORACLE_PORT") == "" && (len(dialed) == 0 || dialed[0] != want) {
			t.Fatalf("dialed %v, want %s", dialed, want)
		}
	})

	t.Run("Server", func(t *testing.T) {
		info, err := c.Server(ctx)
		if err != nil {
			t.Fatal(err)
		}
		if info.Product != "Oracle Database" || info.Version == "" || info.User != user || info.Extras["Container"] == "" {
			t.Fatalf("server info %+v", info)
		}
	})

	t.Run("Schemas", func(t *testing.T) {
		list, err := c.Schemas(ctx, "")
		if err != nil {
			t.Fatal(err)
		}
		if len(list) == 0 || list[0].Name != user || list[0].System {
			t.Fatalf("first schema %+v, want %s", list[:min(len(list), 1)], user)
		}
		sys := false
		for _, s := range list {
			if s.Name == "SYS" {
				sys = s.System
			}
		}
		if !sys {
			t.Fatal("SYS should be a system schema")
		}
	})

	t.Run("Objects", func(t *testing.T) {
		objs, err := c.Objects(ctx, driver.Scope{})
		if err != nil {
			t.Fatal(err)
		}
		m := objectKinds(objs)
		for _, k := range []string{"table:RS_CUSTOMERS", "table:RS_ORDERS", "table:RS_LOG", "view:RS_CUSTOMER_ORDERS", "sequence:RS_SEQ",
			"procedure:RS_GREET", "package:RS_PKG", "trigger:RS_ORDERS_BI", "type:RS_POINT_T", "synonym:RS_CUST"} {
			if _, ok := m[k]; !ok {
				t.Errorf("missing %s", k)
			}
		}
		if m["table:RS_CUSTOMERS"].Comment != "Customers" {
			t.Errorf("table comment %q", m["table:RS_CUSTOMERS"].Comment)
		}
		if !strings.Contains(m["trigger:RS_ORDERS_BI"].Extra, "BEFORE") || !strings.Contains(m["synonym:RS_CUST"].Extra, "RS_CUSTOMERS") {
			t.Errorf("extras: trigger %q, synonym %q", m["trigger:RS_ORDERS_BI"].Extra, m["synonym:RS_CUST"].Extra)
		}
		if _, ok := m["materialized_view:RS_TOTALS"]; !ok {
			t.Error("missing materialized view")
		}
		if _, ok := m["table:RS_TOTALS"]; ok {
			t.Error("materialized view container listed as a table")
		}
		for _, o := range objs {
			if strings.HasPrefix(o.Name, "ISEQ$$") || strings.HasPrefix(o.Name, "SYS_") {
				t.Errorf("system-generated object listed: %+v", o)
			}
		}
	})

	t.Run("Describe", func(t *testing.T) {
		tbl, err := c.Describe(ctx, driver.ObjectRef{Name: "RS_CUSTOMERS"})
		if err != nil {
			t.Fatal(err)
		}
		if tbl.Kind != "table" || tbl.Ref.Schema != user || tbl.Comment != "Customers" || tbl.RowKeyKind != "primary" || !tbl.Editable {
			t.Fatalf("table %+v", tbl)
		}
		checks := []struct{ name, typ string }{
			{"ID", "NUMBER(10)"}, {"NAME", "VARCHAR2(100 CHAR)"}, {"EMAIL", "VARCHAR2(200 BYTE)"}, {"CREATED", "DATE"},
			{"BALANCE", "NUMBER(12,2)"}, {"NOTES", "CLOB"}, {"AVATAR", "BLOB"}, {"UPDATED_AT", "TIMESTAMP(6)"},
			{"SEEN_AT", "TIMESTAMP(6) WITH TIME ZONE"}, {"SCORE", "BINARY_DOUBLE"},
		}
		for _, ch := range checks {
			if col := column(t, tbl, ch.name); col.Type != ch.typ {
				t.Errorf("%s type %q, want %q", ch.name, col.Type, ch.typ)
			}
		}
		id := column(t, tbl, "ID")
		if id.Kind != driver.KindInt || !id.AutoIncrement || !id.PrimaryKey || id.Default == nil || !strings.Contains(*id.Default, "IDENTITY") {
			t.Errorf("ID %+v", id)
		}
		if n := column(t, tbl, "NAME"); n.Nullable || n.Kind != driver.KindString || n.Length == nil || *n.Length != 100 {
			t.Errorf("NAME %+v", n)
		}
		if b := column(t, tbl, "BALANCE"); b.Kind != driver.KindDecimal || b.Default == nil || *b.Default != "0" {
			t.Errorf("BALANCE %+v", b)
		}
		if v := column(t, tbl, "NAME_UPPER"); v.Generated != `UPPER("NAME")` || v.Default != nil {
			t.Errorf("NAME_UPPER %+v", v)
		}
		if e := column(t, tbl, "EMAIL"); e.Comment != "Login email" {
			t.Errorf("EMAIL comment %q", e.Comment)
		}
		kinds := map[string]driver.ValueKind{"CREATED": driver.KindDateTime, "NOTES": driver.KindText, "AVATAR": driver.KindBinary,
			"UPDATED_AT": driver.KindDateTime, "SEEN_AT": driver.KindTimestamp, "SCORE": driver.KindFloat}
		for name, k := range kinds {
			if col := column(t, tbl, name); col.Kind != k {
				t.Errorf("%s kind %s, want %s", name, col.Kind, k)
			}
		}
		if len(tbl.PrimaryKey) != 1 || tbl.PrimaryKey[0] != "ID" {
			t.Errorf("primary key %v", tbl.PrimaryKey)
		}
		if len(tbl.Checks) != 1 || tbl.Checks[0].Name != "RS_CUSTOMERS_BALANCE_CK" {
			t.Errorf("checks %+v", tbl.Checks)
		}
		var lower, unique, primary bool
		for _, ix := range tbl.Indexes {
			switch {
			case ix.Name == "RS_CUSTOMERS_LOWER_IX":
				lower = len(ix.Columns) == 1 && ix.Columns[0] == `LOWER("EMAIL")`
			case ix.Unique && len(ix.Columns) == 1 && ix.Columns[0] == "EMAIL":
				unique = true
			case ix.Primary:
				primary = true
			}
		}
		if !lower || !unique || !primary {
			t.Errorf("indexes %+v", tbl.Indexes)
		}
		if len(tbl.Referenced) != 1 || tbl.Referenced[0].Name != "RS_ORDERS_CUSTOMER_FK" || tbl.Referenced[0].OnDelete != "CASCADE" ||
			tbl.Referenced[0].Table.Name != "RS_ORDERS" {
			t.Errorf("referenced %+v", tbl.Referenced)
		}
		if !strings.Contains(tbl.DDL, "CREATE TABLE") || !strings.Contains(tbl.DDL, "RS_CUSTOMERS_LOWER_IX") || !strings.Contains(tbl.DDL, "COMMENT ON COLUMN") {
			t.Errorf("DDL:\n%s", tbl.DDL)
		}

		orders, err := c.Describe(ctx, driver.ObjectRef{Schema: user, Name: "RS_ORDERS"})
		if err != nil {
			t.Fatal(err)
		}
		if len(orders.ForeignKeys) != 1 || orders.ForeignKeys[0].RefTable.Name != "RS_CUSTOMERS" || orders.ForeignKeys[0].Columns[0] != "CUSTOMER_ID" ||
			orders.ForeignKeys[0].RefColumns[0] != "ID" {
			t.Errorf("foreign keys %+v", orders.ForeignKeys)
		}
		if len(orders.Triggers) != 1 || orders.Triggers[0].Timing != "BEFORE" || orders.Triggers[0].Event != "INSERT" ||
			!strings.Contains(orders.Triggers[0].Statement, ":NEW.STATUS") {
			t.Errorf("triggers %+v", orders.Triggers)
		}
		for _, ix := range orders.Indexes {
			if ix.Name == "RS_ORDERS_CUSTOMER_IX" && (len(ix.Columns) != 2 || ix.Columns[1] != "PLACED_AT" || !ix.Desc[1]) {
				t.Errorf("descending index %+v", ix)
			}
		}

		logTbl, err := c.Describe(ctx, driver.ObjectRef{Name: "RS_LOG"})
		if err != nil {
			t.Fatal(err)
		}
		if logTbl.RowKeyKind != "rowid" || !logTbl.Editable {
			t.Errorf("keyless table: %s editable=%v", logTbl.RowKeyKind, logTbl.Editable)
		}

		view, err := c.Describe(ctx, driver.ObjectRef{Name: "RS_CUSTOMER_ORDERS"})
		if err != nil {
			t.Fatal(err)
		}
		if view.Kind != "view" || !strings.Contains(strings.ToUpper(view.Definition), "SELECT") || view.Editable || len(view.Columns) != 2 {
			t.Errorf("view %+v", view)
		}
		mv, err := c.Describe(ctx, driver.ObjectRef{Name: "RS_TOTALS"})
		if err != nil {
			t.Fatal(err)
		}
		if mv.Kind != "materialized_view" || !strings.Contains(mv.Definition, "SUM") || mv.Editable || len(mv.Columns) != 2 {
			t.Errorf("materialized view %+v", mv)
		}
		if _, err := c.Describe(ctx, driver.ObjectRef{Name: "RS_NOPE"}); err == nil || !strings.Contains(err.Error(), "not found") {
			t.Errorf("missing table: %v", err)
		}
	})

	t.Run("Definition", func(t *testing.T) {
		cases := map[string][]string{
			"procedure": {"CREATE OR REPLACE PROCEDURE", "DBMS_OUTPUT.PUT_LINE"},
			"package":   {"CREATE OR REPLACE PACKAGE RS_PKG", "CREATE OR REPLACE PACKAGE BODY", "RETURN n * 2"},
			"trigger":   {"CREATE OR REPLACE TRIGGER", ":NEW.STATUS"},
			"type":      {"TYPE", "RS_POINT_T", "OBJECT"},
			"sequence":  {"CREATE SEQUENCE", "RS_SEQ", "INCREMENT BY 5"},
			"synonym":   {"CREATE OR REPLACE SYNONYM", "FOR SHOP.RS_CUSTOMERS"},
			"view":      {"VIEW", "RS_CUSTOMER_ORDERS", "GROUP BY"},
			"table":     {"CREATE TABLE", "RS_ORDERS_CUSTOMER_FK"},
		}
		names := map[string]string{"procedure": "RS_GREET", "package": "RS_PKG", "trigger": "RS_ORDERS_BI", "type": "RS_POINT_T",
			"sequence": "RS_SEQ", "synonym": "RS_CUST", "view": "RS_CUSTOMER_ORDERS", "table": "RS_ORDERS"}
		for kind, want := range cases {
			def, err := c.Definition(ctx, driver.ObjectRef{Name: names[kind], Kind: kind})
			if err != nil {
				t.Errorf("%s: %v", kind, err)
				continue
			}
			for _, w := range want {
				if !strings.Contains(def, strings.Replace(w, "SHOP", user, 1)) {
					t.Errorf("%s definition lacks %q:\n%s", kind, w, def)
				}
			}
		}
	})

	t.Run("CatalogColumns", func(t *testing.T) {
		cat, err := c.CatalogColumns(ctx, driver.Scope{})
		if err != nil {
			t.Fatal(err)
		}
		found := map[string]driver.CatalogTable{}
		for _, ct := range cat {
			found[ct.Name] = ct
		}
		cust, orders, view := found["RS_CUSTOMERS"], found["RS_ORDERS"], found["RS_CUSTOMER_ORDERS"]
		if len(cust.Columns) == 0 || !cust.Columns[0].PK || cust.Columns[0].Type != "NUMBER(10)" {
			t.Errorf("customers %+v", cust)
		}
		if len(orders.FKs) != 1 || view.Kind != "view" {
			t.Errorf("orders fks %+v, view kind %q", orders.FKs, view.Kind)
		}
	})

	t.Run("EditAndBrowse", func(t *testing.T) {
		ref := driver.ObjectRef{Name: "RS_CUSTOMERS"}
		edits := []driver.RowEdit{
			{Op: "insert", Values: map[string]any{"NAME": "Ada", "EMAIL": "ada@example.com", "CREATED": "2024-05-06 07:08:09",
				"BALANCE": "12.50", "NOTES": strings.Repeat("n", 5000), "AVATAR": map[string]any{"$bin": "iVBORw0KGgo="},
				"UPDATED_AT": "2024-05-06T07:08:09.123456", "SEEN_AT": "2024-05-06 07:08:09+02:00", "SCORE": 1.5}},
			{Op: "insert", Values: map[string]any{"NAME": "Grace", "EMAIL": "grace@example.com", "BALANCE": 7}},
			{Op: "insert", Values: map[string]any{"NAME": "Linus", "EMAIL": "linus@example.com", "BALANCE": "0.05"}},
		}
		res, err := c.ApplyEdits(ctx, ref, edits)
		if err != nil {
			t.Fatal(err)
		}
		if res.Applied != 3 {
			t.Fatalf("applied %d", res.Applied)
		}
		page, err := c.Browse(ctx, driver.BrowseRequest{Ref: ref, Sort: []driver.Sort{{Column: "NAME"}}, Limit: 10})
		if err != nil {
			t.Fatal(err)
		}
		if len(page.Rows) != 3 || page.Truncated {
			t.Fatalf("rows %d truncated %v", len(page.Rows), page.Truncated)
		}
		ada := page.Rows[0]
		get := func(name string) any { return ada[resultCol(t, page, name)] }
		if _, ok := get("ID").(int64); !ok {
			t.Errorf("ID encoded as %T", get("ID"))
		}
		want := map[string]any{"NAME": "Ada", "BALANCE": "12.5", "CREATED": "2024-05-06 07:08:09", "UPDATED_AT": "2024-05-06 07:08:09.123456",
			"SEEN_AT": "2024-05-06 07:08:09+02:00", "SCORE": 1.5, "NAME_UPPER": "ADA"}
		for k, v := range want {
			if got := get(k); got != v {
				t.Errorf("%s = %#v, want %#v", k, got, v)
			}
		}
		if notes, _ := get("NOTES").(string); len(notes) != 5000 {
			t.Errorf("NOTES length %d", len(notes))
		}
		if bin, ok := get("AVATAR").(map[string]any); !ok || bin["size"] != 8 {
			t.Errorf("AVATAR %#v", get("AVATAR"))
		}
		if typ := page.Columns[resultCol(t, page, "BALANCE")].Type; typ != "NUMBER(12,2)" {
			t.Errorf("BALANCE result type %q", typ)
		}
		if !strings.Contains(page.SQL, "FETCH NEXT 11 ROWS ONLY") {
			t.Errorf("browse SQL %s", page.SQL)
		}

		filtered := func(req driver.BrowseRequest) []string {
			t.Helper()
			req.Ref = ref
			if req.Limit == 0 {
				req.Limit = 10
			}
			if len(req.Sort) == 0 {
				req.Sort = []driver.Sort{{Column: "NAME"}}
			}
			r, err := c.Browse(ctx, req)
			if err != nil {
				t.Fatalf("browse %+v: %v", req, err)
			}
			var names []string
			for _, row := range r.Rows {
				names = append(names, row[resultCol(t, r, "NAME")].(string))
			}
			return names
		}
		cases := []struct {
			req  driver.BrowseRequest
			want string
		}{
			{driver.BrowseRequest{Filters: []driver.Filter{{Column: "NAME", Op: "contains", Value: "RAC"}}}, "Grace"},
			{driver.BrowseRequest{Filters: []driver.Filter{{Column: "BALANCE", Op: "between", Values: []any{"1", "10"}}}}, "Grace"},
			{driver.BrowseRequest{Filters: []driver.Filter{{Column: "NAME", Op: "in", Values: []any{"Ada", "Linus"}}}}, "Ada,Linus"},
			{driver.BrowseRequest{Filters: []driver.Filter{{Column: "NOTES", Op: "null"}}}, "Grace,Linus"},
			{driver.BrowseRequest{Filters: []driver.Filter{{Column: "EMAIL", Op: "regexp", Value: "^L"}}}, "Linus"},
			{driver.BrowseRequest{Filters: []driver.Filter{{Column: "CREATED", Op: "startswith", Value: "2024-05"}}}, "Ada"},
			{driver.BrowseRequest{Filters: []driver.Filter{{Column: "NAME", Op: "like", Value: "%a%"}}}, "Ada,Grace"},
			{driver.BrowseRequest{Search: "linus@"}, "Linus"},
			{driver.BrowseRequest{Search: "12.5"}, "Ada"},
			{driver.BrowseRequest{Where: "BALANCE > 5"}, "Ada,Grace"},
			{driver.BrowseRequest{Sort: []driver.Sort{{Column: "BALANCE", Desc: true}}, Limit: 1, Offset: 1}, "Grace"},
		}
		for _, tc := range cases {
			if got := strings.Join(filtered(tc.req), ","); got != tc.want {
				t.Errorf("%+v: got %q, want %q", tc.req, got, tc.want)
			}
		}
		// The API decodes numbers as json.Number.
		n, err := c.Count(ctx, driver.BrowseRequest{Ref: ref, Filters: []driver.Filter{{Column: "BALANCE", Op: ">", Value: json.Number("1")}}})
		if err != nil || n.Rows != 2 || !n.Exact {
			t.Errorf("count %+v %v", n, err)
		}

		adaID := get("ID")
		if _, err := c.ApplyEdits(ctx, ref, []driver.RowEdit{{Op: "update", Key: map[string]any{"ID": json.Number(fmt.Sprint(adaID))},
			Values: map[string]any{"BALANCE": json.Number("99.99"), "CREATED": "2025-01-02", "NOTES": map[string]any{"$null": true}}}}); err != nil {
			t.Fatal(err)
		}
		r, err := c.Browse(ctx, driver.BrowseRequest{Ref: ref, Filters: []driver.Filter{{Column: "ID", Op: "=", Value: adaID}}})
		if err != nil || len(r.Rows) != 1 {
			t.Fatalf("browse after update: %v", err)
		}
		if b, cr, nt := r.Rows[0][resultCol(t, r, "BALANCE")], r.Rows[0][resultCol(t, r, "CREATED")], r.Rows[0][resultCol(t, r, "NOTES")]; b != "99.99" || cr != "2025-01-02 00:00:00" || nt != nil {
			t.Errorf("after update: %v %v %v", b, cr, nt)
		}
		if _, err := c.ApplyEdits(ctx, ref, []driver.RowEdit{{Op: "update", Key: map[string]any{"ID": 424242}, Values: map[string]any{"NAME": "x"}}}); err == nil {
			t.Error("updating a missing row should fail")
		}
		if _, err := c.ApplyEdits(ctx, ref, []driver.RowEdit{{Op: "update", Key: map[string]any{"ID": adaID}, Values: map[string]any{"BALANCE": -1}}}); err == nil ||
			!strings.Contains(err.Error(), "RS_CUSTOMERS_BALANCE_CK") || strings.Contains(err.Error(), "error occur") {
			t.Errorf("check violation: %v", err)
		}
		if _, err := c.ApplyEdits(ctx, ref, []driver.RowEdit{{Op: "delete", Key: map[string]any{"ID": adaID}}}); err != nil {
			t.Fatal(err)
		}

		// A keyless table is edited through ROWID.
		logRef := driver.ObjectRef{Name: "RS_LOG"}
		if _, err := c.ApplyEdits(ctx, logRef, []driver.RowEdit{
			{Op: "insert", Values: map[string]any{"MSG": "one", "AT": "2024-01-01 10:00:00"}},
			{Op: "insert", Values: map[string]any{"MSG": "two"}},
			{Op: "insert", Values: map[string]any{}},
		}); err != nil {
			t.Fatal(err)
		}
		lr, err := c.Browse(ctx, driver.BrowseRequest{Ref: logRef, Filters: []driver.Filter{{Column: "MSG", Op: "=", Value: "one"}}})
		if err != nil || len(lr.Rows) != 1 {
			t.Fatalf("browse log: %v %d", err, len(lr.Rows))
		}
		rowid := lr.Rows[0][resultCol(t, lr, sqlbase.HiddenRowKey)]
		if s, _ := rowid.(string); s == "" {
			t.Fatalf("rowid %#v", rowid)
		}
		if _, err := c.ApplyEdits(ctx, logRef, []driver.RowEdit{{Op: "update", Key: map[string]any{sqlbase.HiddenRowKey: rowid}, Values: map[string]any{"MSG": "uno"}}}); err != nil {
			t.Fatal(err)
		}
		if _, err := c.ApplyEdits(ctx, logRef, []driver.RowEdit{{Op: "delete", Key: map[string]any{sqlbase.HiddenRowKey: rowid}}}); err != nil {
			t.Fatal(err)
		}
		if n, err := c.Count(ctx, driver.BrowseRequest{Ref: logRef}); err != nil || n.Rows != 2 {
			t.Errorf("log rows %+v %v", n, err)
		}

		if mr, err := c.Browse(ctx, driver.BrowseRequest{Ref: driver.ObjectRef{Name: "RS_TOTALS"}}); err != nil || len(mr.Rows) != 0 {
			t.Errorf("browse materialized view: %v", err)
		}

		// Object-type columns are shown by type name instead of breaking the page.
		sr, err := c.Browse(ctx, driver.BrowseRequest{Ref: driver.ObjectRef{Name: "RS_SHAPES"}})
		if err != nil {
			t.Fatal(err)
		}
		if pt := sr.Rows[0][resultCol(t, sr, "PT")]; pt != "("+user+".RS_POINT_T)" {
			t.Errorf("object column %#v", pt)
		}
	})

	t.Run("Modern", func(t *testing.T) {
		if _, err := c.db.ExecContext(ctx, modernFixture); err != nil {
			t.Skipf("BOOLEAN/JSON/VECTOR columns unavailable: %v", err)
		}
		ref := driver.ObjectRef{Name: "RS_MODERN"}
		tbl, err := c.Describe(ctx, ref)
		if err != nil {
			t.Fatal(err)
		}
		if column(t, tbl, "FLAG").Kind != driver.KindBool || column(t, tbl, "DOC").Kind != driver.KindJSON || column(t, tbl, "V").Kind != driver.KindText {
			t.Errorf("modern kinds %+v", tbl.Columns)
		}
		if _, err := c.ApplyEdits(ctx, ref, []driver.RowEdit{
			{Op: "insert", Values: map[string]any{"ID": 1, "FLAG": true, "DOC": `{"a":[1,2]}`, "V": "[1,2,3]"}},
			{Op: "insert", Values: map[string]any{"ID": 2, "FLAG": false}},
		}); err != nil {
			t.Fatal(err)
		}
		r, err := c.Browse(ctx, driver.BrowseRequest{Ref: ref, Search: "a"})
		if err != nil || len(r.Rows) != 1 {
			t.Fatalf("browse modern: %v", err)
		}
		row := r.Rows[0]
		if row[resultCol(t, r, "FLAG")] != true || row[resultCol(t, r, "DOC")] != `{"a":[1,2]}` || r.Columns[resultCol(t, r, "DOC")].Kind != driver.KindJSON {
			t.Errorf("modern row %#v", row)
		}
		if v, _ := row[resultCol(t, r, "V")].(string); !strings.HasPrefix(v, "[") {
			t.Errorf("vector %#v", row[resultCol(t, r, "V")])
		}
		all, err := c.Browse(ctx, driver.BrowseRequest{Ref: ref, Sort: []driver.Sort{{Column: "ID"}}})
		if err != nil || len(all.Rows) != 2 || all.Rows[1][resultCol(t, all, "FLAG")] != false {
			t.Errorf("flags %v %v", all, err)
		}
	})

	t.Run("Session", func(t *testing.T) {
		sess, err := c.NewSession(ctx, driver.Scope{})
		if err != nil {
			t.Fatal(err)
		}
		defer sess.Close()
		script := `CREATE TABLE RS_TMP (ID NUMBER PRIMARY KEY, V VARCHAR2(20), DOC CLOB);
INSERT INTO RS_TMP (ID, V) VALUES (1, 'a');
BEGIN
  INSERT INTO RS_TMP (ID, V) VALUES (2, 'b');
  DBMS_OUTPUT.PUT_LINE('inserted two');
  RS_GREET('world');
END;
/
SELECT ID, V, DOC, CAST(1.5 AS NUMBER(5,2)) AS X, SYSDATE AS D FROM RS_TMP ORDER BY ID;
EXEC RS_GREET('exec')`
		out := run(t, sess, script, driver.ExecOptions{MaxRows: 100, StopOnError: true})
		if len(out.stmts) != 5 {
			t.Fatalf("statements %d", len(out.stmts))
		}
		for _, st := range out.stmts {
			if st.err != nil {
				t.Fatalf("statement %q: %v", st.info.SQL, st.err)
			}
		}
		if n := out.stmts[2].notices; len(n) != 2 || n[0] != "output: inserted two" || n[1] != "output: Hello, world" {
			t.Errorf("block notices %q", n)
		}
		if out.stmts[2].info.Line != 3 {
			t.Errorf("block line %d", out.stmts[2].info.Line)
		}
		sel := out.stmts[3]
		if len(sel.rows) != 2 || len(sel.cols) != 1 || sel.cols[0][2].Type != "CLOB" || sel.cols[0][1].Type != "VARCHAR2" || sel.rows[0][3] != "1.5" {
			t.Errorf("select cols %+v rows %v", sel.cols, sel.rows)
		}
		if n := out.stmts[4].notices; len(n) != 1 || n[0] != "output: Hello, exec" {
			t.Errorf("exec notices %q", n)
		}
		if !sess.InTransaction() {
			t.Error("inserts should leave a transaction open")
		}
		// The second run sees the uncommitted rows; other connections do not.
		out = run(t, sess, "SELECT COUNT(*) FROM RS_TMP", driver.ExecOptions{})
		if out.stmts[0].err != nil || out.stmts[0].rows[0][0] != "2" {
			t.Errorf("same session count %v %v", out.stmts[0].rows, out.stmts[0].err)
		}
		if n, err := c.Count(ctx, driver.BrowseRequest{Ref: driver.ObjectRef{Name: "RS_TMP"}}); err != nil || n.Rows != 0 {
			t.Errorf("other connection sees %+v %v", n, err)
		}
		out = run(t, sess, "ROLLBACK;\nSELECT COUNT(*) FROM RS_TMP", driver.ExecOptions{})
		if out.stmts[1].rows[0][0] != "0" || sess.InTransaction() {
			t.Errorf("after rollback %v in tx %v", out.stmts[1].rows, sess.InTransaction())
		}

		// Errors point at the right script line.
		out = run(t, sess, "SELECT 1 FROM DUAL;\nBEGIN\n  NULL;\n  undefined_x := 1;\nEND;\n/", driver.ExecOptions{})
		if qe := queryErr(t, out.stmts[1].err); qe.Line != 4 || qe.Code != "ORA-06550" || !strings.HasPrefix(qe.Message, "PLS-00201") {
			t.Errorf("PL/SQL compile error %+v", qe)
		}
		out = run(t, sess, "\nBEGIN\n  RAISE_APPLICATION_ERROR(-20001, 'boom');\nEND;", driver.ExecOptions{})
		if qe := queryErr(t, out.stmts[0].err); qe.Line != 3 || qe.Code != "ORA-20001" || qe.Message != "ORA-20001: boom" {
			t.Errorf("runtime error %+v", qe)
		}
		out = run(t, sess, "SELECT 1 FROM DUAL;\nSELECT *\n  FROM RS_NO_SUCH_TABLE", driver.ExecOptions{})
		if qe := queryErr(t, out.stmts[1].err); qe.Line != 3 || qe.Code != "ORA-00942" || qe.Position == 0 || strings.Contains(qe.Message, "error occur") {
			t.Errorf("SQL error %+v", qe)
		}
		out = run(t, sess, "CREATE OR REPLACE PROCEDURE RS_BAD IS\nBEGIN\n  undefined_y := 1;\nEND;\n/\nSELECT 1 FROM DUAL", driver.ExecOptions{})
		if qe := queryErr(t, out.stmts[0].err); qe.Line != 3 || qe.Code != "PLS-00201" || !strings.Contains(qe.Detail, "compilation errors") {
			t.Errorf("compilation error %+v", qe)
		}
		if out.stmts[1].err != nil {
			t.Errorf("statement after a compilation error: %v", out.stmts[1].err)
		}

		// A result go-ora cannot decode resets the console instead of breaking it.
		out = run(t, sess, "SELECT PT FROM RS_SHAPES", driver.ExecOptions{})
		if !errors.Is(out.stmts[0].err, errDriverFailure) {
			t.Errorf("object column: %v", out.stmts[0].err)
		}
		out = run(t, sess, "SELECT 'ok' FROM DUAL", driver.ExecOptions{})
		if out.stmts[0].err != nil || out.stmts[0].rows[0][0] != "ok" {
			t.Errorf("after reconnect: %v %v", out.stmts[0].rows, out.stmts[0].err)
		}

		// A cancelled statement leaves the console usable.
		cctx, cancel := context.WithTimeout(ctx, 500*time.Millisecond)
		cs := &recSink{}
		_ = sess.Execute(cctx, "SELECT COUNT(*) FROM ALL_OBJECTS a, ALL_OBJECTS b, ALL_OBJECTS c", driver.ExecOptions{}, cs)
		cancel()
		if len(cs.stmts) != 1 || cs.stmts[0].err == nil {
			t.Fatalf("cancelled statement: %+v", cs.stmts)
		}
		out = run(t, sess, "SELECT 'still ok' FROM DUAL", driver.ExecOptions{})
		if out.stmts[0].err != nil || out.stmts[0].rows[0][0] != "still ok" {
			t.Errorf("after cancel: %v %v", out.stmts[0].rows, out.stmts[0].err)
		}

		// Read-only runs are enforced by the classifier.
		out = run(t, sess, "INSERT INTO RS_LOG (MSG) VALUES ('x');\nSELECT 1 FROM DUAL", driver.ExecOptions{ReadOnly: true})
		if out.stmts[0].err == nil || out.stmts[1].err != nil {
			t.Errorf("read-only: %v / %v", out.stmts[0].err, out.stmts[1].err)
		}
	})

	t.Run("SessionScope", func(t *testing.T) {
		sess, err := c.NewSession(ctx, driver.Scope{Schema: "SYS"})
		if err != nil {
			t.Fatal(err)
		}
		defer sess.Close()
		out := run(t, sess, "SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') FROM DUAL", driver.ExecOptions{})
		if out.stmts[0].err != nil || out.stmts[0].rows[0][0] != "SYS" {
			t.Errorf("current schema %v %v", out.stmts[0].rows, out.stmts[0].err)
		}
	})

	t.Run("Explain", func(t *testing.T) {
		plan, err := c.Explain(ctx, driver.Scope{}, "SELECT * FROM RS_ORDERS WHERE CUSTOMER_ID = 1;", false)
		if err != nil {
			t.Fatal(err)
		}
		if plan.Root == nil || plan.Root.Operation != "SELECT STATEMENT" || len(plan.Root.Children) == 0 || !strings.Contains(plan.Raw, "Plan hash value") {
			t.Fatalf("plan %+v\n%s", plan.Root, plan.Raw)
		}
		if _, err := c.Explain(ctx, driver.Scope{}, "SELECT * FROM RS_NOPE", false); err == nil {
			t.Error("explaining a bad statement should fail")
		}
		if _, err := c.Explain(ctx, driver.Scope{}, "SELECT * FROM RS_ORDERS", true); err != nil && !strings.Contains(err.Error(), "SELECT access") {
			t.Errorf("analyze as app user: %v", err)
		}
	})

	t.Run("Admin", func(t *testing.T) {
		tolerate := func(what string, err error) {
			if err != nil && !strings.Contains(err.Error(), "needs SELECT access") {
				t.Errorf("%s: %v", what, err)
			}
		}
		_, err := c.Processes(ctx)
		tolerate("processes", err)
		_, err = c.Variables(ctx, "variables")
		tolerate("variables", err)
		_, err = c.Variables(ctx, "status")
		tolerate("status", err)
		users, err := c.Users(ctx)
		if err != nil || len(users.Rows) == 0 || users.Columns[0].Name != "user" {
			t.Errorf("users %v", err)
		}
		grants, err := c.UserGrants(ctx, user)
		if err != nil || len(grants) == 0 {
			t.Errorf("grants %q %v", grants, err)
		}
		for _, id := range []string{"1", "1,2,3", "1; DROP TABLE x", "a,b", ""} {
			if err := c.KillProcess(ctx, id); err == nil || !strings.Contains(err.Error(), "invalid session id") {
				t.Errorf("kill %q: %v", id, err)
			}
		}
	})

	t.Run("ReadOnly", func(t *testing.T) {
		rp := testParams(t, appUser(), pw)
		rp.ReadOnly = true
		ro := mustOpen(t, rp)
		if _, err := ro.ApplyEdits(ctx, driver.ObjectRef{Name: "RS_LOG"}, []driver.RowEdit{{Op: "insert", Values: map[string]any{"MSG": "x"}}}); !errors.Is(err, driver.ErrReadOnly) {
			t.Errorf("read-only edit: %v", err)
		}
	})

	t.Run("System", func(t *testing.T) {
		sp := testParams(t, "system", systemPassword())
		octx, cancel := context.WithTimeout(ctx, time.Minute)
		defer cancel()
		sc, err := oracleDriver{}.Open(octx, sp)
		if err != nil {
			t.Skipf("SYSTEM login unavailable: %v", err)
		}
		defer sc.Close()
		s := sc.(*conn)
		objs, err := s.Objects(ctx, driver.Scope{Schema: user})
		if err != nil {
			t.Fatal(err)
		}
		if o, ok := objectKinds(objs)["table:RS_CUSTOMERS"]; !ok || o.Size == nil {
			t.Errorf("customers as SYSTEM %+v", o)
		}
		tbl, err := s.Describe(ctx, driver.ObjectRef{Schema: user, Name: "RS_CUSTOMERS"})
		if err != nil || !strings.Contains(tbl.DDL, "CREATE TABLE") {
			t.Errorf("describe as SYSTEM: %v", err)
		}
		plan, err := s.Explain(ctx, driver.Scope{Schema: user}, "SELECT * FROM RS_CUSTOMERS WHERE BALANCE > 1", true)
		if err != nil {
			t.Fatal(err)
		}
		if plan.Root == nil || plan.Root.ActualRows == nil || plan.Totals["Execution Time"] == nil {
			t.Errorf("analyze plan %+v\n%s", plan.Root, plan.Raw)
		}
		for _, kind := range []string{"variables", "status"} {
			if res, err := s.Variables(ctx, kind); err != nil || len(res.Rows) == 0 {
				t.Errorf("%s: %v", kind, err)
			}
		}
		grants, err := s.UserGrants(ctx, user)
		if err != nil || len(grants) == 0 || !strings.HasPrefix(grants[0], "GRANT ") {
			t.Errorf("grants of %s: %q %v", user, grants, err)
		}

		// Kill a session of the app user and see it go.
		victim := mustOpen(t, testParams(t, appUser(), pw))
		vc, err := victim.db.Conn(ctx)
		if err != nil {
			t.Fatal(err)
		}
		defer vc.Close()
		var sid, serial string
		if err := vc.QueryRowContext(ctx, `SELECT SYS_CONTEXT('USERENV', 'SID') FROM DUAL`).Scan(&sid); err != nil {
			t.Fatal(err)
		}
		procs, err := s.Processes(ctx)
		if err != nil {
			t.Fatal(err)
		}
		for _, row := range procs.Rows {
			if id, _ := row[0].(string); strings.HasPrefix(id, sid+",") {
				serial = strings.TrimPrefix(id, sid+",")
			}
		}
		if serial == "" {
			t.Fatalf("session %s not listed", sid)
		}
		if err := s.KillProcess(ctx, sid+","+serial); err != nil {
			t.Fatal(err)
		}
		if err := vc.QueryRowContext(ctx, `SELECT 1 FROM DUAL`).Scan(new(int)); err == nil {
			t.Error("killed session still works")
		}
	})

	t.Run("SID", func(t *testing.T) {
		sp := testParams(t, "system", systemPassword())
		sp.Params["service"], sp.Params["serviceType"] = "FREE", "sid"
		octx, cancel := context.WithTimeout(ctx, time.Minute)
		defer cancel()
		sc, err := oracleDriver{}.Open(octx, sp)
		if err != nil {
			t.Skipf("no SID FREE on this server: %v", err)
		}
		defer sc.Close()
		info, err := sc.Server(ctx)
		if err != nil || info.Extras["Container"] == "" {
			t.Errorf("server over SID: %+v %v", info, err)
		}
	})
}
